project:
  type: website

website:
  title: "Methods"
  back-to-top-navigation: true
  navbar:
    logo: img/egap-logo.svg
    logo-width: 500px
    search: true
    right:
      - file: index.qmd
        text: Home
      - file: guides.qmd
        text: Methods guides
      - file: software.qmd
        text: Software
      - file: coursebook/index.qmd
        text: Coursebook
      
  sidebar:
    - title: "Coursebook"
      contents:
        - coursebook/index.qmd
        - coursebook/researchdesignform.qmd
        - coursebook/causalinference.qmd
        - coursebook/randomization.qmd
        - coursebook/hypothesistesting.qmd
        - coursebook/estimation.qmd
        - coursebook/statisticalpower.qmd
        - coursebook/measurement.qmd
        - coursebook/references.qmd
        
    - title: "Guides"
    
    - title: ""
      id: effect-types 
      style: docked
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        # - text: "What is a simulation?"
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/research-questions/effect-types.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/research-questions/effect-types.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/research-questions/effect-types.es.html
              
format:
  html:
    theme: 
      - simplex
      - theme.scss
    css: styles.css
    linkcolor: blue
    toc: true
    toc-location: body
    code-overflow: wrap
    number-sections: true
    abstract-title: Summary
    template-partials:
      - partials/title-block.html
      - partials/toc.html

execute:
  freeze: auto
  cache: true

