project:
  type: website

website:
  title: "Methods for Impact Evaluations"
  navbar:
    logo: img/egap-logo.svg
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: guides.qmd
        text: Guides
      - about.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



