project:
  type: website
  render:
    - "*.qmd"
    - "guides/**/*.qmd"
    - "!CLAUDE.md"
    - "!HANDOFF.md"
    - "!MIGRATION_PLAN.md"
    - "!README.md"

website:
  title: "Methods"
  back-to-top-navigation: true
  navbar:
    logo: img/egap-logo.svg
    logo-width: 500px
    search: true
    right:
      - file: index.qmd
        text: Home
      - file: guides.qmd
        text: Methods guides
      - file: software.qmd
        text: Software
      - file: teaching.qmd
        text: Teaching

  sidebar:

    - title: ""
      # contents:
      #   - text: "How to read this guide"
      #     href: /guides/how-to-read_en.html

    - title: "Guides"

    - title: ""
      id: effect-types
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        # - text: "What is a simulation?"
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/research-questions/effect-types_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/research-questions/effect-types_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/research-questions/effect-types_es.html

    # - title: ""
    #   id: hypothesis-testing
    #   contents:
    #     - text: "How to read this guide"
    #       href: /guides/how-to-read_en.html
    #     - text: "Language"
    #       contents:
    #         - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
    #           href: /guides/analysis-procedures/hypothesis-testing_en.html
    #         - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
    #           href: /guides/analysis-procedures/hypothesis-testing_fr.html
    #         - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
    #           href: /guides/analysis-procedures/hypothesis-testing_es.html

    - title: ""
      id: external-validity
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/assessing-designs/external-validity_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/assessing-designs/external-validity_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/assessing-designs/external-validity_es.html

    - title: ""
      id: power
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/assessing-designs/power_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/assessing-designs/power_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/assessing-designs/power_es.html

    - title: ""
      id: mechanisms
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/research-questions/mechanisms_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/research-questions/mechanisms_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/research-questions/mechanisms_es.html

    - title: ""
      id: pap
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/planning/pap_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/planning/pap_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/planning/pap_es.html

    - title: ""
      id: xcausey
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/causal-inference/x-cause-y_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/causal-inference/x-cause-y_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/causal-inference/x-cause-y_es.html

    - title: ""
      id: causal-inference
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/causal-inference/causal-inference_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/causal-inference/causal-inference_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/causal-inference/causal-inference_es.html

    - title: ""
      id: measurement
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/data-collection/measurement_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/data-collection/measurement_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/data-collection/measurement_es.html

    - title: ""
      id: randomization
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read_en.html
        - text: "Language"
          contents:
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/data-collection/randomization_en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/data-collection/randomization_fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/data-collection/randomization_es.html


format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    linkcolor: blue
    toc: true
    toc-location: body
    toc-depth: 1
    code-overflow: wrap
    code-fold: true
    number-sections: true
    abstract-title: Summary
    template-partials:
      - partials/title-block.html
      - partials/toc.html

execute:
  freeze: auto
  cache: true

