project:
  type: website

website:
  title: "EGAP Learning"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - guides.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



