project:
  type: website

website:
  title: "Methods"
  back-to-top-navigation: true
  navbar:
    logo: img/egap-logo.svg
    logo-width: 500px
    search: true
    right:
      - file: index.qmd
        text: Home
      - file: guides.qmd
        text: Methods guides
      - file: software.qmd
        text: Software
      - file: teaching.qmd
        text: Teaching
      
  sidebar:

    - title: ""
      # contents: 
      #   - text: "How to read this guide"
      #     href: /guides/how-to-read.html
        
    - title: "Guides"
    
    - title: ""
      id: effect-types 
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        # - text: "What is a simulation?"
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/research-questions/effect-types.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/research-questions/effect-types.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/research-questions/effect-types.es.html
        
    - title: ""
      id: hypothesis-testing
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/analysis-procedures/hypothesis-testing.en.html
            # - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
            #   href: /guides/analysis-procedures/hypothesis-testing.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/analysis-procedures/hypothesis-testing.es.html

    - title: ""
      id: external-validity
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/assessing-designs/external-validity.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/assessing-designs/external-validity.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/assessing-designs/external-validity.es.html

    - title: ""
      id: power
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/assessing-designs/power.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/assessing-designs/power.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/assessing-designs/power.es.html

    - title: ""
      id: mechanisms
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/research-questions/mechanisms.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/research-questions/mechanisms.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/research-questions/mechanisms.es.html

    - title: ""
      id: pap
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/planning/pap.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/planning/pap.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/planning/pap.es.html

    - title: ""
      id: xcausey
      contents:
        - text: "How to read this guide"
          href: /guides/how-to-read.html
        - text: "Language"
          contents: 
            - text: "<img src='https://flagcdn.com/w20/gb.png' width=20px>&nbsp;&nbsp;English"
              href: /guides/causal-inference/x-cause-y.en.html
            - text: "<img src='https://flagcdn.com/w20/fr.png' width=20px>&nbsp;&nbsp;French"
              href: /guides/causal-inference/x-cause-y.fr.html
            - text: "<img src='https://flagcdn.com/w20/es.png' width=20px>&nbsp;&nbsp;Spanish"
              href: /guides/causal-inference/x-cause-y.es.html


format:
  html:
    theme: 
      - simplex
      - theme.scss
    css: styles.css
    linkcolor: blue
    toc: true
    toc-location: body
    toc-depth: 1
    code-overflow: wrap
    number-sections: true
    abstract-title: Summary
    template-partials:
      - partials/title-block.html
      - partials/toc.html

execute:
  freeze: auto
  cache: true

