<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paul Testa">

<title>10 types d’effets de traitement à connaître – Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../img/egap-logo.svg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../guides.html"> 
<span class="menu-text">Methods guides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../software.html"> 
<span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.en.html">Language</a></li><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.fr.html"><img src="https://flagcdn.com/w20/fr.png" width="20px">&nbsp;&nbsp;French</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/how-to-read.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to read this guide</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true">
 <span class="menu-text">Language</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.en.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><img src="https://flagcdn.com/w20/gb.png" width="20px">&nbsp;&nbsp;English</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.fr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><img src="https://flagcdn.com/w20/fr.png" width="20px">&nbsp;&nbsp;French</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.es.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><img src="https://flagcdn.com/w20/es.png" width="20px">&nbsp;&nbsp;Spanish</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.en.html">Language</a></li><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.fr.html"><img src="https://flagcdn.com/w20/fr.png" width="20px">&nbsp;&nbsp;French</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">10 types d’effets de traitement à connaître</h1>
</div>

<div class="quarto-title-meta">
    
    
    
    
</div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Summary</div>
    <p>Voir ce guide<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> pour une discussion plus formelle sur l’indépendance et les hypothèses nécessaires pour estimer les effets causaux. Ce guide décrit dix types distincts d’effets causaux que les chercheurs peuvent souhaiter estimer. Comme discuté dans notre guide sur l’inférence causale, la randomisation simple permet de produire des estimations de la moyenne des effets causaux au niveau de l’unité dans un échantillon. Cet effet causal moyen ou effet moyen du traitement (average treatment effect, ATE) est un concept puissant car c’est une solution à l’impossibilité d’observer tous les contrefactuels pertinents. Pourtant, ce n’est pas la seule manière efficace de faire face à ce problème. En fait, il existe de nombreux types différents de quantités d’intérêt causal. L’objectif de ce guide est de vous aider à choisir des paramètres (i.e.&nbsp;des paramètres d’intérêt) et des estimateurs (procédures pour calculer des estimations de ces paramètres) qui sont appropriés et significatifs pour vos données.</p>
  </div>
</div>
</header>

<nav id="TOC" role="doc-toc">
    <h4 id="toc-title">Contents</h4>
   
  <ul>
  <li><a href="#effet-moyen-du-traitement" id="toc-effet-moyen-du-traitement"><span class="header-section-number">1</span> Effet moyen du traitement</a></li>
  <li><a href="#effet-moyen-du-traitement-conditionnel" id="toc-effet-moyen-du-traitement-conditionnel"><span class="header-section-number">2</span> Effet moyen du traitement conditionnel</a></li>
  <li><a href="#effet-dintention-de-traiter-intent-to-treat-effect-itt" id="toc-effet-dintention-de-traiter-intent-to-treat-effect-itt"><span class="header-section-number">3</span> Effet d’intention de traiter (intent to treat effect, ITT)</a></li>
  <li><a href="#effet-causal-moyen-pour-ceux-qui-se-conforment-au-traitement-complier-average-causal-effect-cace" id="toc-effet-causal-moyen-pour-ceux-qui-se-conforment-au-traitement-complier-average-causal-effect-cace"><span class="header-section-number">4</span> Effet causal moyen pour ceux qui se conforment au traitement (complier average causal effect, CACE)</a></li>
  <li><a href="#effet-moyen-du-traitement-dune-population-ou-dun-échantillon" id="toc-effet-moyen-du-traitement-dune-population-ou-dun-échantillon"><span class="header-section-number">5</span> Effet moyen du traitement d’une population ou d’un échantillon</a></li>
  <li><a href="#effet-moyen-du-traitement-sur-les-traités-et-le-contrôle" id="toc-effet-moyen-du-traitement-sur-les-traités-et-le-contrôle"><span class="header-section-number">6</span> Effet moyen du traitement sur les traités et le contrôle</a></li>
  <li><a href="#effet-moyen-du-traitement-par-quantile" id="toc-effet-moyen-du-traitement-par-quantile"><span class="header-section-number">7</span> Effet moyen du traitement par quantile</a></li>
  <li><a href="#effet-de-médiation" id="toc-effet-de-médiation"><span class="header-section-number">8</span> Effet de médiation</a></li>
  <li><a href="#effet-du-traitement-log-odds" id="toc-effet-du-traitement-log-odds"><span class="header-section-number">9</span> Effet du traitement Log-Odds</a></li>
  <li><a href="#effet-attribuable" id="toc-effet-attribuable"><span class="header-section-number">10</span> Effet attribuable</a></li>
  <li><a href="#références" id="toc-références"><span class="header-section-number">11</span> Références</a></li>
  </ul>
</nav>
<section id="effet-moyen-du-traitement" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Effet moyen du traitement</h1>
<p>Nous commençons par examiner comment, avec la randomisation, une simple différence des moyennes fournit une estimation non biaisée de l’ATE. Nous prenons plus de temps pour présenter certains concepts et notations statistiques courants utilisés tout au long de ce guide.</p>
<p>Tout d’abord, nous définissons un effet de traitement pour une observation individuelle (une personne, un ménage, une ville, etc.) comme la différence entre le comportement de cette unité sous le traitement <span class="math inline">\(Y_{i}(1)\)</span> et sous le contrôle <span class="math inline">\(Y_{i}( 0)\)</span> :</p>
<p><span class="math display">\[τ_{i}=Y_{i}(1)−Y_{i}(0)\]</span></p>
<p>Puisque nous ne pouvons observer que <span class="math inline">\(Y_{i}(1)\)</span> ou <span class="math inline">\(Y_{i}(0)\)</span>, l’effet du traitement individuel est impossible à connaître. Soit <span class="math inline">\(D_{i}\)</span> un indicateur pour savoir si c’est une observation sous traitement ou sous contrôle. Si le traitement est assigné de manière aléatoire, <span class="math inline">\(D_{i}\)</span> est indépendant, non seulement des résultats potentiels mais aussi de toutes les covariables (observées et non observées) qui pourraient également prédire ces résultats <span class="math inline">\((Y_{i}(1), Y_{i }(0) et X_{i}⊥⊥D_{i})\)</span>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Supposons que notre conception implique <span class="math inline">\(m\)</span> unités sous traitement et <span class="math inline">\(N−m\)</span> sous contrôle. Supposons que nous devions réassigner à plusieurs reprises le traitement de manière aléatoire et à chaque fois calculer la différence des moyennes entre les groupes de traitement et de contrôle, puis enregistrer cette valeur dans une liste. La moyenne des valeurs de cette liste sera la même que la différence des moyennes des véritables résultats potentiels si nous avions observé tous les résultats potentiels pour toutes les observations.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Autrement dit, l’estimateur (i.e.&nbsp;la différence des moyennes observées) est un estimateur sans biais de l’effet causal moyen du traitement.</p>
<p><span class="math display">\[ATE≡\frac{1}{N}∑^{N}_{i=1}τ_{i}=\frac{∑^{N}_{1}Y_{i}(1)}{N}−\frac{∑^{N}_{1}Y_{i}(0)}{N}\]</span></p>
<p>Et nous estimons souvent l’ATE en utilisant la différence des moyennes observées:<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p><span class="math display">\[\widehat{ATE} =\frac{∑^m_1Z_{i}Y_{i}}{m}−\frac{∑^{N}_{m+1}(1−Z_{i})Y_{i}}{N−m}\]</span></p>
<p>L’inférence statistique sur l’ATE estimé nécessite que nous sachions comment il variera selon les randomisations. Il s’avère que nous pouvons écrire la variance de l’ATE à travers les randomisations comme suit :</p>
<p><span class="math display">\[V(ATE) = \frac{N}{N−1} [\frac{V(Y_{i}(1))}{m}+\frac{V(Y_{i}(0))}{N−m}]−\frac{1}{N−1}[V(Y_{i}(1))+V(Y_{i}(0))−2∗Cov(Y_{i}(1),Y_{i}(0))]\]</span></p>
<p>et estimer cette quantité à partir des estimations de l’échantillon de la variance dans chaque groupe.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Un modèle linéaire de régression du résultat observé <span class="math inline">\(Y_{i}\)</span> sur un indicateur de traitement <span class="math inline">\(D_{i}\)</span> fournit un estimateur pratique de l’ATE (et avec quelques ajustements supplémentaires, de la variance de l’ATE) :</p>
<p><span class="math display">\[Y_{i}=Y_{i}(0)∗(1−D_{i})+Y_{i}(1)∗D_{i}=β_{0}+β_{1}D_{i}+u\]</span></p>
<p>puisque nous pouvons réarranger les termes de sorte que <span class="math inline">\(β_{0}\)</span> représente la moyenne parmi les observations de contrôle <span class="math inline">\((Y_{i}(0)∣D_{i}=0)\)</span> et <span class="math inline">\(β_{1}\)</span> représente la différence des moyennes <span class="math inline">\((Y_{i}(1)∣D_{i}=1)–(Y_{i}(1)∣D_{i}=0)\)</span>. Dans le code ci-dessous, nous créons un échantillon de 1 000 observations et assignons de manière aléatoire un traitement Di avec un effet unitaire constant à la moitié des unités. Nous estimons l’ATE en utilisant la méthode des moindres carrés ordinaires (MCO) pour calculer la différence des moyennes observée. Le calcul des moyennes dans chaque groupe et la prise de leur différence produiraient également une estimation non biaisée de l’ATE. Notez que l’ATE estimé à partir de MCO n’est pas biaisé, mais les erreurs dans ce modèle linéaire sont supposées être indépendantes et distribuées de manière identique. Lorsque notre traitement affecte à la fois la valeur moyenne du résultat et la distribution des réponses, cette hypothèse ne tient plus et nous devons ajuster l’erreur type de MCO à l’aide d’un estimateur sandwich Huber-White pour obtenir les estimations correctes (basées sur la variance de l’ATE) pour l’inférence statistique.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Enfin, nous démontrons également l’absence de biais de ces estimateurs par simulation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(N) <span class="co"># Résultat potentiel sous la condition de contrôle</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="co"># Résultat potentiel sous condition de traitement</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>N)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Traitement: 1 si traité, 0 sinon</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat dans la population</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y) </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ATE <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp))[<span class="dv">2</span>] <span class="co"># idem avec (samp,mean(Y[Z==1])-mean(Y[Z==0]))</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># SATE avec Neyman ou avec une erreur type justifiée par randomisation</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># qui sont les mêmes que les erreurs types MCO en l'absence de covariables ou de découpage par bloc</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest) </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich) </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp) </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fit))[<span class="st">"D"</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Estimate Std. Error 
1.01820525 0.01841784 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ATE.se<span class="ot">&lt;-</span><span class="fu">coeftest</span>(fit,<span class="fu">vcovHC</span>(fit,<span class="at">type=</span><span class="st">"HC2"</span>))[<span class="st">"D"</span>,<span class="dv">2</span>] </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># idem avec (samp,sqrt(var(Y[D==1])/sum(D)+var(Y[D==0])/(n-sum(D)))</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Évaluer le biais et simuler l'erreur type</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>getATE<span class="ot">&lt;-</span><span class="cf">function</span>() {</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>N)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Traitement: 1 si traité, 0 sinon</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D))[[<span class="st">"D"</span>]] </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>manyATEs<span class="ot">&lt;-</span><span class="fu">replicate</span>(<span class="dv">10000</span>,<span class="fu">getATE</span>()) </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Évaluer le biais:</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">ATE=</span><span class="fu">mean</span>(Y1)<span class="sc">-</span><span class="fu">mean</span>(Y0), <span class="at">ExpEstATE=</span><span class="fu">mean</span>(manyATEs)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ATE ExpEstATE 
1.0000000 0.9999077 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Erreur type</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">### en utilisant la formule classique</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>V<span class="ot">&lt;-</span><span class="fu">var</span>(<span class="fu">cbind</span>(Y0,Y1)) </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>varc<span class="ot">&lt;-</span>V[<span class="dv">1</span>,<span class="dv">1</span>] </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>vart<span class="ot">&lt;-</span>V[<span class="dv">2</span>,<span class="dv">2</span>] </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>covtc<span class="ot">&lt;-</span>V[<span class="dv">1</span>,<span class="dv">2</span>] </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="fu">sum</span>(D) </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span>N<span class="sc">-</span>n </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>varestATE<span class="ot">&lt;-</span>((N<span class="sc">-</span>n)<span class="sc">/</span>(N<span class="dv">-1</span>))<span class="sc">*</span>(vart<span class="sc">/</span>n) <span class="sc">+</span> ((N<span class="sc">-</span>m)<span class="sc">/</span>(N<span class="dv">-1</span>))<span class="sc">*</span> (varc<span class="sc">/</span>m) <span class="sc">+</span> (<span class="dv">2</span><span class="sc">/</span>(N<span class="dv">-1</span>)) <span class="sc">*</span> covtc </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="do">### Comparer les erreurs types</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SimulatedSE=</span> <span class="fu">sd</span>(manyATEs), <span class="at">TrueSE=</span><span class="fu">sqrt</span>(varestATE), <span class="at">ConservativeSE=</span>ATE.se) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   SimulatedSE         TrueSE ConservativeSE 
    0.01835497     0.01842684     0.01841784 </code></pre>
</div>
</div>
</section>
<section id="effet-moyen-du-traitement-conditionnel" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Effet moyen du traitement conditionnel</h1>
<p>Le problème de ne considérer que l’effet moyen du traitement est que cela détourne l’attention du fait que l’effet du traitement peut être très différent pour différents types de personnes. Alors que le “problème fondamental de l’inférence causale” suggère que la mesure des effets causaux pour des unités individuelles est impossible, faire des inférences sur des groupes d’unités ne l’est pas.</p>
<p>L’assignation aléatoire garantit que le traitement est indépendant des résultats potentiels et de toute covariable (observée et non observée). Parfois, cependant, nous avons des informations supplémentaires sur les unités expérimentales telles qu’elles existaient avant que l’expérience ne soit menée, disons <span class="math inline">\(X_{i}\)</span>, et ces informations peuvent nous aider à comprendre comment les effets du traitement varient entre les sous-groupes. Par exemple, nous pouvons suspecter que les hommes et les femmes réagissent différemment au traitement, et nous pouvons tester cette hétérogénéité en estimant l’ATE conditionnel pour chaque sous-groupe séparément <span class="math inline">\(CATE=E(Y_{i}(1)−Y_{i}(0 )∣D_{i},X_{i})\)</span>. Si notre covariable est continue, nous pouvons tester ses effets modérateurs en faisant varier la variable continue avec le traitement. Notez, cependant, que l’effet du traitement est désormais conditionné à la fois au statut du traitement et à la valeur de la variable de conditionnement pour laquelle l’effet est évalué, nous devons donc ajuster notre interprétation et l’erreur type en conséquence.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Avertissement : examiner l’effet du traitement à travers des dimensions qui sont elles-mêmes influencées par le traitement est une entreprise dangereuse et peut conduire à des inférences incorrectes. Par exemple, si vous vouliez voir comment l’administration d’un médicament conduit à des améliorations de la santé, vous pouvez rechercher séparément les hommes et les femmes, mais vous ne pouvez pas rechercher séparément ceux qui ont effectivement pris le médicament et ceux qui ne l’ont pas fait (ceci est un exemple d’inférence pour conformistes qui nécessite des techniques distinctes décrites au point 4 ci-dessous).</p>
</section>
<section id="effet-dintention-de-traiter-intent-to-treat-effect-itt" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Effet d’intention de traiter (intent to treat effect, ITT)</h1>
<p>En dehors de l’environnement contrôlé d’un laboratoire, les sujets que nous assignons au traitement ne sont souvent pas les mêmes que les sujets qui reçoivent réellement le traitement. Lorsque certains sujets assignés au traitement ne le reçoivent pas, nous appelons cela une expérience de non-conformité unilatérale. Lorsqu’en plus, certains sujets assignés au contrôle reçoivent également le traitement, on dit qu’il y a non-conformité bilatérale. Par exemple, dans une expérience de vote, certaines personnes désignées pour recevoir un courrier peuvent ne pas le recevoir. Peut-être ont-ils changé d’adresse ou ne consultent-ils jamais leur courrier. De même, certaines observations assignées au contrôle peuvent recevoir le traitement. Peut-être qu’ils viennent d’emménager et que le courrier du locataire précédent arrive toujours.</p>
<p>En cas de non-conformité, la réception du traitement n’est plus indépendante des résultats potentiels et des facteurs de confusion. Les personnes qui relèvent réellement leur courrier diffèrent probablement à plusieurs égards de celles qui jettent leur courrier (ou lisent le courrier de leurs voisins) et ces différences affectent probablement également leur probabilité de voter. La différence des moyennes entre les sujets assignés au traitement et au contrôle n’estime plus l’ATE, mais estime à la place ce qu’on appelle l’effet d’intention de traiter (ITT). Nous interprétons souvent l’ITT comme l’effet de donner à quelqu’un la possibilité de recevoir un traitement. L’ITT est donc particulièrement pertinent pour évaluer les programmes et les interventions à participation volontaire.</p>
<p>Dans le code ci-dessous, nous créons des données simples avec une non-conformité unilatérale. Bien que le véritable effet du traitement pour les personnes qui ont effectivement reçu le traitement soit de 2, notre ITT estimé est plus petit (environ 1) car seules certaines des personnes assignées au traitement le reçoivent réellement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Résultat potentiel sous la condition de contrôle</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>C <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># L'unité se conforme ou non au traitement</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span>C <span class="co"># Résultat potentiel sous condition de traitement</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Assignation du traitement</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> Z<span class="sc">*</span>C <span class="co"># Adoption du traitement</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat dans la population</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(Z,Y)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>ITT<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>Z,<span class="at">data=</span>samp))[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-causal-moyen-pour-ceux-qui-se-conforment-au-traitement-complier-average-causal-effect-cace" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Effet causal moyen pour ceux qui se conforment au traitement (complier average causal effect, CACE)</h1>
<p>Que se passe-t-il si vous souhaitez déterminer l’effet du traitement sur les personnes qui ont effectivement suivi le traitement et pas seulement sur celles à qui le traitement a été administré ? Par exemple, quel est l’effet des publicités à la radio sur le comportement de vote des personnes qui entendent réellement les publicités ?</p>
<p>Cela s’avère être un problème difficile (pour en savoir plus à ce sujet, consultez <a href="https://TODO">ce guide</a>). Les raisons de non-conformité au traitement peuvent être considérées comme une variable omise. Alors que la réception du traitement n’est plus indépendante des résultats potentiels, l’assignation du statut de traitement l’est. Tant que l’assignation aléatoire a eu un effet positif sur la probabilité de recevoir un traitement, nous pouvons l’utiliser comme instrument pour identifier l’effet du traitement sur la sous-population de sujets qui se conforment à l’assignation du traitement.</p>
<p>Suivant la notation d’Angrist et Pischke,<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> soit <span class="math inline">\(Z\)</span> un indicateur pour savoir si une observation a été assignée au traitement et <span class="math inline">\(D_{i}\)</span> indique si ce sujet a effectivement reçu le traitement. Les expériences avec non-conformité sont composées de “toujours preneurs” (<span class="math inline">\(D_{i}=1\)</span>, indépendamment de <span class="math inline">\(Z_{i}\)</span>), de “jamais-preneurs” (<span class="math inline">\(D_{i}=0\)</span> indépendamment de <span class="math inline">\(Z_{i}\)</span>), et de conformistes (<span class="math inline">\(D_{i}=1\)</span> lorsque <span class="math inline">\(Z_{i}=1\)</span> et <span class="math inline">\(0\)</span> lorsque <span class="math inline">\(Z_{i}=0\)</span>).<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> Nous pouvons estimer l’effet causal moyen pour les conformistes (CACE), parfois aussi appelé effet moyen local du traitement (local average treatment effect, LATE), en pondérant l’ITT (l’effet de <span class="math inline">\(Z\)</span> sur <span class="math inline">\(Y\)</span>) par l’efficacité de l’assignation aléatoire sur la prise de traitement (l’effet de <span class="math inline">\(Z\)</span> sur <span class="math inline">\(D\)</span>).</p>
<p><span class="math display">\[CACE= \frac{Effet de Z sur Y}{Effet de Z sur D}=\frac{E(Y_i|Z_i=1)-E(Y_i|Z_i=0)}{E(D_i|Z_i=1)-E(D_i|Z_i=0)}\]</span></p>
<p>L’estimateur ci-dessus met en évidence le fait que l’ITT et le CACE convergent à mesure que nous approchons d’une conformité totale. Calculer l’erreur type pour les ratios est quelque peu fastidieux et nous estimons donc généralement un CACE en utilisant une régression des moindres carrés en deux étapes avec assignation aléatoire, <span class="math inline">\(Z_i\)</span>, servant d’instrument pour la réception du traitement <span class="math inline">\(D_i\)</span> dans la première étape du modèle. Cette approche simplifie l’estimation de l’erreur type et permet l’inclusion de covariables en tant qu’instruments supplémentaires. Dans le code ci-dessous, nous présentons les deux stratégies pour les données présentant une non-conformité bilatérale. Notez, cependant, que lorsque les instruments ne sont pas puissants (par exemple, l’assignation aléatoire n’a eu qu’un faible effet sur la réception du traitement), les estimateurs des variables instrumentales et leurs erreurs types peuvent être biaisés et incohérents.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Résultat potentiel sous la condition de contrôle</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="co"># Résultat potentiel sous condition de traitement</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Assignation du traitement</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pD<span class="ot">&lt;-</span><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">mean=</span><span class="dv">2</span><span class="sc">*</span>Z)) <span class="co"># Non-conformité</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>D<span class="ot">&lt;-</span><span class="fu">rbinom</span>(n,<span class="dv">1</span>,pD) <span class="co"># Réception du traitement avec non-conformité</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat dans la population</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(Z,D,Y) </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># IV estimate library(AER) CACE = coef(ivreg(Y ~ D | Z, data = samp))[2] </span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Wald Estimator ITT&lt;-coef(lm(Y~Z,data=samp))[2] ITT.D&lt;-coef(lm(D~Z,data=samp))[2] CACE.wald&lt;-ITT/ITT.D</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-moyen-du-traitement-dune-population-ou-dun-échantillon" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Effet moyen du traitement d’une population ou d’un échantillon</h1>
<p>Souvent, à partir de notre échantillon, nous voulons en tirer des généralisations pour une population d’intérêt plus large.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> Soit <span class="math inline">\(S_i\)</span> un indicateur pour savoir si un sujet fait partie de notre échantillon. L’effet moyen du traitement pour l’échantillon (sample average treatment effect, SATE) est défini simplement comme <span class="math inline">\(E(Y_i(1)−Y_i(0)|S_i=1)\)</span> et la population <span class="math inline">\(E(Y_i(1)−Y_i(0))\)</span>. Avec un grand échantillon aléatoire d’une population bien définie et une conformité totale au traitement, nos SATE et PATE sont égaux en espérance et donc une bonne estimation de l’un (comme une différence des moyennes d’échantillon) sera une bonne estimation de l’autre.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<p>Dans la pratique, l’échantillon expérimental peut consister en un groupe d’unités sélectionnées de manière inconnue à partir d’une population vaguement définie de ces unités et la conformité à l’assignation du traitement peut être moins que complète. Dans de tels cas, notre SATE peut diverger du PATE et la récupération des estimations de chacun devient plus compliquée. Imai, King et Stuart (2008) décomposent la divergence entre ces estimations en erreurs résultant de la sélection de l’échantillon et du déséquilibre de traitement. L’erreur de sélection de l’échantillon provient de différentes distributions de covariables (observées et non observées) dans notre échantillon et notre population. Par exemple, les personnes participant à un essai médical diffèrent souvent de la population pour laquelle le médicament sera disponible. L’erreur due au déséquilibre de traitement reflète les différences de covariables entre les groupes de traitement et de contrôle dans notre échantillon, peut-être en raison d’une assignation non aléatoire et/ou d’une non-conformité.</p>
<p>Bien qu’il n’y ait pas de solutions simples aux problèmes créés par de telles erreurs, vous pouvez prendre des mesures à la fois dans la conception de votre étude et dans l’analyse de vos données pour relever ces défis liés à l’estimation du PATE ou du CACE/LATE. Par exemple, l’inclusion d’une intervention placebo fournit des informations supplémentaires sur la probabilité de recevoir un traitement, qui peuvent être utilisées pour repondérer l’effet de le recevoir réellement en présence de non-conformité (voir par exemple Nickerson (2008)). On pourrait également utiliser un modèle pour repondérer les observations afin d’ajuster le déséquilibre des covariables et la probabilité inégale de recevoir le traitement, à la fois au sein de l’échantillon et entre un échantillon et la population d’intérêt.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<p>Dans le code ci-dessous, nous présentons plusieurs approches pour estimer ces effets mis en œuvre dans le package CausalGAM de R.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> Plus précisément, le package produit des estimateurs de l’ATE par régression, par pondération inverse du score de propension (inverse-propensity weighting, IPW) et par pondération IPW augmentée (augmented IPW, AIPW). En combinant l’ajustement de régression avec l’IPW, l’AIPW a la particularité d’être “doublement robuste” : l’estimation est toujours cohérente même si nous avons incorrectement spécifié le modèle de régression ou le score de propension pour la pondération de probabilité.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exemple adapté de ?estimate.ATE</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CausalGAM) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># covariables de pré-traitement</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># Probabilité de traitement inégale</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) <span class="co"># traitement</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Résultats potentiels</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span> X1 <span class="sc">+</span> X2 </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultats observés</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X1,X2,D,Y) </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimer l'ATE avec l'AIPW, l'IPW ou une régression pondérée</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>ATE.out <span class="ot">&lt;-</span> <span class="fu">estimate.ATE</span>(<span class="at">pscore.formula =</span> D <span class="sc">~</span> X1 <span class="sc">+</span>X2, </span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                        <span class="at">pscore.family =</span> binomial, </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.formula.t =</span> Y <span class="sc">~</span> X1 </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span>X2, </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.formula.c =</span> Y <span class="sc">~</span> X1 </span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span>X2, </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.family =</span> gaussian, </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                        <span class="at">treatment.var =</span> <span class="st">"D"</span>, </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data=</span>samp, </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                        <span class="at">divby0.action=</span><span class="st">"t"</span>, </span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>                        <span class="at">divby0.tol=</span><span class="fl">0.001</span>, </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.gam.plot=</span><span class="cn">FALSE</span>, <span class="at">nboot=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-moyen-du-traitement-sur-les-traités-et-le-contrôle" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Effet moyen du traitement sur les traités et le contrôle</h1>
<p>Pour évaluer les implications politiques d’une intervention particulière, nous avons souvent besoin de connaître l’effet du traitement non seulement sur l’ensemble de la population mais spécifiquement pour ceux à qui le traitement est administré. Nous définissons l’effet moyen du traitement pour les traitées (ATT) et le contrôle (ATC) comme de simples comparaisons contrefactuelles :</p>
<p><span class="math display">\[ATT=E(Y_i(1)-Y_i(0)|D_i=1)=E(Y_i(1)|D_i=1)-E(Y_i(0)|D_i=1)\]</span> <span class="math display">\[ATC=E(Y_i(1)-Y_i(0)|D_i=0)=E(Y_i(1)|D_i=0)-E(Y_i(0)|D_i=0)\]</span></p>
<p>Simplement, l’ATT est l’effet pour ceux que nous avons traités ; l’ATC est ce que l’effet <em>serait</em> pour ceux que nous n’avons pas traités.</p>
<p>Lorsque le traitement est assigné de manière aléatoire et que la conformité est totale, <span class="math inline">\(ATE=ATT=ATC\)</span>, puisque <span class="math inline">\(E(Y_i(0)∣D_i=1)=E(Y_i(0)∣D_i=0)\)</span> et <span class="math inline">\(E( Y_i(1)∣D_i=0)=E(Y_i(1)∣D_i=1)\)</span>. Souvent, en raison de la nature de l’intervention ou de préoccupations ethniques ou spécifiques au coût, la conformité du traitement est incomplète et l’ATE ne sera pas en général égal à l’ATT ou l’ATC. Dans de tels cas, nous avons vu dans la section précédente que nous pouvions repondérer les observations par leur probabilité de recevoir le traitement pour récupérer les estimations de l’ATE. La même logique peut être étendue pour produire des estimations de l’ATT et de l’ATC dans notre échantillon et dans la population.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
<p>Ci-dessous, nous créons une étude de cas où la probabilité de recevoir un traitement varie mais peut être estimée à l’aide d’un modèle de score de propension.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> Les probabilités prédites à partir de ce modèle sont ensuite utilisées comme pondérations pour récupérer les estimations de l’ATE, de l’ATT et de l’ATC. Une pondération inverse du score de propension tente d’équilibrer la distribution des covariables entre les groupes de traitement et de contrôle lors de l’estimation de l’ATE. Pour l’ATT, cette approche de pondération traite les sujets du groupe traité comme un échantillon de la population cible (personnes ayant reçu le traitement) et pondère les sujets du groupe de contrôle en fonction de leur probabilité de recevoir le traitement. De la même manière, l’estimation de l’ATC pondère les observations pour les traités pour qu’elles ressemblent au contrôle. La qualité (l’absence de biais) de ces estimations est intrinsèquement liée à la qualité de nos modèles pour prédire la réception du traitement. La pondération inverse du score de propension et d’autres procédures produisent un équilibre entre les groupes de traitement et de contrôle sur les covariables observées. Mais à moins d’avoir le “vrai modèle” (et nous ne connaissons presque jamais le vrai modèle), le potentiel biais des covariables non observées demeure et devrait nous conduire à interpréter notre ATT ou ATC estimé à la lumière de la qualité du modèle qui l’a produit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># covariables de pré-traitement</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># probabilité de traitement inégale</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) <span class="co"># traitement</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># résultats potentiels</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span><span class="dv">1</span> <span class="sc">+</span>X1 <span class="sc">+</span>X2 </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># résultats observés</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X1,X2,D,Y) </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># modèle du score de propension</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>p.score<span class="ot">&lt;-</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="fu">glm</span>(D<span class="sc">~</span>X1<span class="sc">+</span>X2,samp,<span class="at">family=</span>binomial),<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># pondération inverse du score de propension</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.ipw<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span><span class="sc">/</span>p.score,<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p.score))) </span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.att<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span>,p.score<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p.score))) </span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.atc<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,(<span class="dv">1</span><span class="sc">-</span>p.score)<span class="sc">/</span>p.score,<span class="dv">1</span>)) </span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># IPW: ATE, ATT, ATC </span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>ATE.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.ipw))[<span class="dv">2</span>]</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>ATT.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.att))[<span class="dv">2</span>] </span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>ATC.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.atc))[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-moyen-du-traitement-par-quantile" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Effet moyen du traitement par quantile</h1>
<p>L’ATE se concentre sur le milieu, en quelque sorte sur l’effet pour une personne typique, mais nous nous soucions souvent aussi des conséquences distributives de notre traitement. Nous voulons savoir non seulement si notre traitement a augmenté le revenu moyen, mais aussi s’il a rendu la distribution des revenus dans l’étude plus ou moins égale.</p>
<p>Les affirmations concernant les distributions sont difficiles. Même si nous pouvons estimer l’ATE à partir d’une différence des moyennes d’échantillon, en général, nous ne pouvons pas faire de déclarations sur la distribution conjointe des résultats potentiels <span class="math inline">\(F(Yi(1),Yi(0))\)</span> sans hypothèse supplémentaire. En règle générale, ces hypothèses limitent notre analyse à une sous-population spécifique<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> ou nous obligent à supposer une certaine forme d’invariance de rang dans la distribution des réponses à l’effet du traitement<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a>. Voir Frölich et Melly (2010) pour une discussion assez concise sur ces questions. Voir Abbring et Heckman (Abbring, Jaap H et James J Heckman. 2007. “Econometric Evaluation of Social Programs, Part III : Distributional Treatment Effects, Dynamic Treatment Effects, Dynamic Discrete Choice, and General Equilibrium Policy Evaluation”. Handbook of Econometrics 6. Elsevier: 5145-5303.) pour un aperçu complet.</p>
<p>Si ces hypothèses sont justifiées pour nos données, nous pouvons obtenir des estimations cohérentes de l’effet du traitement par quantile (quantile treatment effect, QTE) en utilisant la régression par quantile.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> Tout comme la régression linéaire estime l’ATE comme une différence des moyennes (ou, lorsque des covariables sont utilisées dans le modèle, à partir d’une moyenne conditionnelle), la régression par quantile ajuste un modèle linéaire à un quantile conditionnel et ce modèle peut ensuite être utilisé pour estimer l’effet du traitement pour ce quantile particulier du résultat. L’approche peut être étendue pour inclure des covariables et des instruments de non-conformité. Notez que l’interprétation du QTE est pour un quantile donné, non pas pour un individu de ce quantile.</p>
<p>Ci-dessous, nous montrons un cas où l’ATE est de 0, mais l’effet du traitement est négatif pour les faibles quantiles du résultat et positif pour les quantiles élevés. L’estimation de l’effet du traitement par quantile fournit un autre outil pour détecter les effets hétérogènes et nous permet de décrire les conséquences distributionnelles de notre intervention. Ces informations supplémentaires nécessitent des hypothèses statistiques plus strictes pour nos données et des interprétations plus nuancées de nos résultats.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Résultat potentiel sous la condition de contrôle</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>Y1<span class="ot">=</span> Y0 </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>Y1[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>] <span class="ot">=</span> Y0[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>]<span class="sc">-</span><span class="fu">rnorm</span>(<span class="fu">length</span>(Y0[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>])) </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>Y1[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>] <span class="ot">=</span> Y0[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>]<span class="sc">+</span><span class="fu">rnorm</span>(<span class="fu">length</span>(Y0[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>])) </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Traitement: 1 si traité, 0 sinon</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat dans la population</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y) </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantreg) </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ATE <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp))[<span class="dv">2</span>] </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>QTE <span class="ot">=</span> <span class="fu">rq</span>(Y<span class="sc">~</span>D,<span class="at">tau =</span> </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(.<span class="dv">05</span>,.<span class="dv">95</span>,<span class="at">length.out=</span><span class="dv">10</span>),<span class="at">data=</span>samp,<span class="at">method =</span> <span class="st">"fn"</span>) </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(QTE),<span class="at">parm=</span><span class="dv">2</span>,<span class="at">main=</span><span class="st">""</span>,<span class="at">ylab=</span><span class="st">"QTE"</span>,<span class="at">xlab=</span><span class="st">"Quantile"</span>,<span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">2.1</span>, <span class="fl">2.1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="effect-types.fr_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="effet-de-médiation" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Effet de médiation</h1>
<p>Parfois, nous voulons décrire non seulement l’ampleur et le niveau de signification d’un effet causal observé, mais aussi le mécanisme (ou les mécanismes) qui l’ont produit. Notre intervention a-t-elle augmenté la participation dans le groupe de traitement, en partie, en augmentant le sentiment d’utilité politique pour ces sujets ? Si oui, quelle part de cet effet total peut être attribuée aux effets de médiation de notre traitement sur le sentiment d’utilité ; et de ce sentiment d’utilité sur la participation au vote ?</p>
<p>Baron et Kenny (1986) proposent un cadre général de réflexion sur la médiation en décomposant l’effet total du traitement en son effet indirect sur un médiateur qui affecte ensuite le résultat, appelé effet causal moyen de médiation (average causal mediation effect, ACME), et l’effet moyen direct du traitement (average direct effect, ADE). L’estimation non biaisée de ces effets, cependant, nécessite un ensemble d’hypothèses fortes sur la relation entre le traitement, les médiateurs, les résultats et les facteurs de confusion potentiels, collectivement appelés ignorabilité séquentielle (Imai, Keele et Yamamoto (2010), Bullock, Green et Ha (2010 )).<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></p>
<p>La plupart des effets causaux opèrent probablement à travers plusieurs canaux, et donc une hypothèse d’ignorabilité séquentielle pour votre expérience peut être difficile à justifier. Par exemple, la ligne du haut de la figure ci-dessous illustre des situations dans lesquelles l’ignorabilité séquentielle est valable, tandis que la ligne du bas décrit deux cas (parmi de nombreux possibles) dans lesquels l’ignorabilité séquentielle est violée et l’analyse de médiation est biaisée. En essence, la spécification des effets d’un médiateur particulier nécessite des hypothèses fortes sur le rôle de tous les autres médiateurs dans la chaîne causale. Alors que certains modèles expérimentaux peuvent, en théorie, fournir un effet de levier supplémentaire (comme l’exécution d’une deuxième expérience parallèle dans laquelle le médiateur est également manipulé), en pratique, ces modèles sont difficiles à mettre en œuvre et restent sensibles aux biais non observés. Dans certains cas, les informations que nous espérons tirer de l’analyse de médiation peuvent être plus facilement acquises à partir d’analyses de sous-groupes et d’expériences conçues pour tester la modération.</p>
<p>Imai et ses collègues proposent une approche de l’analyse de médiation qui permet aux chercheurs de tester la sensibilité de leurs estimations aux violations de l’ignorabilité séquentielle.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a> Dans le code, nous montrons certaines des caractéristiques de leur approche, implémentée dans le package “mediation” en R (Tingley et al.&nbsp;2014). Nous modélisons les relations avec MCO, mais le package est capable de gérer d’autres processus de résultats, tels que des modèles linéaires généralisés ou des modèles additifs généralisés, qui peuvent être plus appropriés pour vos données. Plus important encore, le package nous permet de produire les bornes qui reflètent la sensibilité de nos estimations ponctuelles à certaines violations de l’ignorabilité séquentielle. Dans nos données simulées, un peu plus de 20 % de l’effet total est médié par notre médiateur proposé, M et le biais d’un facteur de confusion pré-traitement non observé devrait être assez important (ρ = 0,7) avant que nous rejetions la conclusion d’un ACME positif. Ces limites ne sont toutefois valables que si nous pensons qu’il n’y a pas de facteurs de confusion post-traitement non observés (comme dans le panneau 4). L’analyse de sensibilité est toujours possible, mais plus compliquée dans de tels contextes (Imai et Yamamoto 2013).</p>
<p><img src="https://raw.githubusercontent.com/egap/methods-guides/master/effect-types/effect-types_fig2.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Résultat potentiel sous la condition de contrôle</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Traitement: 1 si traité, 0 sinon</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">rnorm</span>(n) <span class="co"># Covariable</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>M<span class="ot">&lt;-</span><span class="fu">rnorm</span>(<span class="at">n=</span>n,<span class="at">mean=</span>D<span class="sc">+</span><span class="fu">rnorm</span>(n)) <span class="co"># Médiateur impacté par le traitement</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span> M <span class="co"># Résultat potentiel sous condition de traitement</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat dans la population</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>samp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(D,M,Y) </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation) </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>med.f<span class="ot">&lt;-</span><span class="fu">lm</span>(M<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp) <span class="co"># Modèle pour le médiateur</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>out.f<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>M<span class="sc">+</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp) <span class="co"># Modèle pour le résultat</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimer ACME et ADE</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation) </span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>med.out<span class="ot">&lt;-</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mediate</span>(med.f,out.f,<span class="at">treat=</span><span class="st">"D"</span>,<span class="at">mediator=</span><span class="st">"M"</span>,<span class="at">robustSE=</span>T,<span class="at">sims=</span><span class="dv">1000</span>) </span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Sensibilité de l'ACME à un facteur de confusion pré-traitement non observé</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>s.out<span class="ot">&lt;-</span><span class="fu">medsens</span>(med.out) </span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(s.out) <span class="co"># Tracer les bornes de la sensibilité</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="effect-types.fr_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Structural equations estimates of ACME ADE </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># f1&lt;-formula(Y~D+X) </span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># f2&lt;-formula(M~D+X) </span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># f3&lt;-formula(Y~D+M+X) </span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># med.sys&lt;-systemfit(list(f1,f2,f3),data=samp) </span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ACME&lt;-coef(med.sys)["eq1_D"]-coef(med.sys)["eq3_D"] </span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ADE&lt;-coef(med.sys)["eq3_D"]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-du-traitement-log-odds" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Effet du traitement Log-Odds</h1>
<p>L’effet moyen du traitement semble un peu difficile à interpréter lorsque les résultats ne sont pas continus. Par exemple, un résultat binaire très courant dans l’étude des élections est codé comme 1 lorsque les sujets ont voté et 0 lorsqu’ils ne l’ont pas fait. L’effet moyen peut être de 0,2, mais qu’est-ce que cela signifie vraiment de dire qu’un traitement a augmenté mon vote de 0,2 ? L’estimation des effets causaux des résultats dichotomiques nécessite des précautions supplémentaires, en particulier lors de l’inclusion de covariables. Une quantité commune d’intérêt causal pour les résultats dichotomiques est l’effet du traitement sur les log-odds de succès, défini pour l’échantillon expérimental comme :</p>
<p><span class="math display">\[\Delta = log\frac{E(Y_i(1))}{1-E(Y_i(1))} - log\frac{E(Y_i(0))}{1-E(Y_i(0))}\]</span></p>
<p>Freedman (2008b) montre que l’ajustement de covariables dans une régression logistique dans les expériences randomisées produit des estimations biaisées de cet effet causal. L’intuition de base de l’argument de Freedman vient du fait que prendre le log des moyennes n’est pas la même chose que prendre la moyenne des logs et donc le coefficient de traitement estimé à partir d’une régression logistique conditionnée aux covariables ne fournira pas un estimateur cohérent des log-odds de succès. Au lieu de cela, Freedman recommande de prendre les probabilités prédites de variation du statut de traitement des sujets, mais de maintenir leurs profils de covariables observés pour produire un estimateur cohérent des log-odds.</p>
<p>La procédure de base est décrite dans le code ci-dessous. Les coefficients de la régression logistique contrôlant la covariable X ont tendance à surestimer l’effet du traitement sur les log odds, tandis que les estimations ajustées à partir des probabilités prédites produisent des résultats cohérents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>U <span class="ot">=</span> <span class="fu">runif</span>(n) </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Covariable observée</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">ifelse</span>(U<span class="sc">&gt;</span>.<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">0</span>) <span class="co"># Résultats potentiels</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> <span class="fu">ifelse</span>(U<span class="sc">+</span>X<span class="sc">&gt;</span>.<span class="dv">75</span>,<span class="dv">1</span>,<span class="dv">0</span>) </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n,<span class="dv">1</span>,.<span class="dv">75</span>) <span class="co"># Assignation aléatoire des 3/4 au traitement</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1<span class="sc">+</span>Y0<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>D) </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X,D,Y) </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>aT<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">mean</span>(Y[D<span class="sc">==</span><span class="dv">1</span>])) </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>aC<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">mean</span>(Y[D<span class="sc">==</span><span class="dv">0</span>])) </span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># log odds sans conditions</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>log.odds<span class="ot">&lt;-</span><span class="fu">log</span>(aT<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>aT))<span class="sc">-</span><span class="fu">log</span>(aC<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>aC)) </span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># La régression logistique conditionnée sur X surestime les log odds</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">glm</span>(Y<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp,<span class="fu">binomial</span>(<span class="st">"logit"</span>)) </span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>log.odds.logit<span class="ot">&lt;-</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="fu">glm</span>(Y<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp,<span class="fu">binomial</span>(<span class="st">"logit"</span>)))[<span class="dv">2</span>] </span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframes utilisant les covariables initiales pour les probabilités prédites</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>D1<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">D=</span><span class="dv">1</span>,samp[,<span class="fu">c</span>(<span class="st">"X"</span>)]) </span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>D0<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">D=</span><span class="dv">0</span>,samp[,<span class="fu">c</span>(<span class="st">"X"</span>)]) </span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Les log-odds ajustés produisent un estimateur consistent des log-cotes</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>aT.adj<span class="ot">&lt;-</span><span class="fu">predict</span>(fit,<span class="at">newdata=</span>D1,<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>aC.adj<span class="ot">&lt;-</span><span class="fu">predict</span>(fit,<span class="at">newdata=</span>D0,<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>log.odds.adj<span class="ot">&lt;-</span><span class="fu">log</span>(<span class="fu">mean</span>(aT.adj)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(aT.adj)))<span class="sc">-</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(<span class="fu">mean</span>(aC.adj)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(aC.adj)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="effet-attribuable" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Effet attribuable</h1>
<p>Nous concluons par une brève discussion sur une autre quantité d’intérêt causal qui peut être particulièrement utile avec des résultats binaires : l’effet attribuable (Rosenbaum 2010). Considérons un cas simple avec un résultat dichotomique et un traitement. Soit <span class="math inline">\(A\)</span> le nombre de résultats attribuables au traitement, c’est-à-dire le nombre de cas pour lesquels <span class="math inline">\(Y_i\)</span> était égal à 1 parmi les sujets traités ; ce qui ne se serait pas produit si ces unités avaient été assignées au contrôle. Pour une plage de <span class="math inline">\(A\)</span>, nous ajustons le tableau de contingence observée des résultats parmi les traités et comparons cette distribution résultante à une distribution nulle connue (la distribution des résultats que nous aurions observée si le traitement n’avait eu aucun effet). La plage résultante de <span class="math inline">\(A\)</span> pour laquelle notre test continue de rejeter l’hypothèse nulle d’absence d’effet fournit une plage des effets qui sont attribuables à notre traitement.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Table 1</th>
<th><span class="math inline">\(D=1\)</span></th>
<th><span class="math inline">\(D=0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y=1\)</span></td>
<td><span class="math inline">\(\sum Y_iD_i-A\)</span></td>
<td><span class="math inline">\((1-Y_i)(D_i)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Y=0\)</span></td>
<td><span class="math inline">\(\sum Y_i(1-D_i)+A\)</span></td>
<td><span class="math inline">\(\sum (1-Y_i)(1-D_i)\)</span></td>
</tr>
</tbody>
</table>
<p>Rosenbaum (2002) étend ce concept à différents types de résultats (tels que les variables continues). Une logique similaire peut également être appliquée pour détecter des réponses inhabituelles mais importantes au traitement (Rosenbaum et Silber 2008).</p>
<p>Hansen et Bowers (2009) utilisent cette approche pour identifier le nombre de votes supplémentaires attribuables à différentes interventions incitant au vote avec une assignation de traitement par grappe et une non-conformité unilatérale. Ils montrent que, dans de grands échantillons, on peut approximer l’intervalle de confiance pour les effets attribuables sans évaluer chaque attribution. Voici un exemple de cette approche où des covariables sont utilisées pour augmenter la précision.</p>
<p>Premièrement, nous définissons un effet attribuable comme <span class="math inline">\(A=∑_iZ_iτ_i\)</span>, où <span class="math inline">\(τ_i=Y_i(1)−Y_i(0)\)</span> et <span class="math inline">\(y∈0,1\)</span> selon Rosenbaum (2002). C’est-à-dire que l’effet attribuable est le nombre de réponses “oui” ou “1” parmi les personnes traitées que nous n’aurions pas vues si elles avaient été dans le groupe de contrôle.</p>
<p>Deuxièmement, notez que si nous écrivons l’ensemble <span class="math inline">\(U\)</span> comme échantillon expérimental et que l’ensemble des unités de contrôle est un sous-ensemble de l’ensemble, <span class="math inline">\(C⊆U\)</span>, alors nous pouvons écrire <span class="math inline">\(∑_{i∈C}Y_i −Y_i(0)=0\)</span>. Cela signifie que nous pouvons représenter <span class="math inline">\(A\)</span> ainsi :</p>
<span class="math display">\[A = ∑_{i=1}^NZ_iτ_i=∑_{i=1}^NZ_i(Y_i(1)−Y_i(0))=∑_{i∉C}y_i(1)−∑_{i∉C}y_i(0)\]</span> <span class="math display">\[  = ∑_{i∉C}Y_i−∑_{i∉C}Y_i(0)=∑_{i=1}^NY_i−∑_{i=1}^NY_i(0)=t_U−t_C\]</span>
<center>
= total observé globalement (fixe et observé) - résultat total sous contrôle (non observé, à estimer)
</center>
<p>Troisièmement, cette représentation nous permet de produire un intervalle de confiance basé sur une conception pour A^ en s’appuyant sur la littérature sur l’échantillonnage pour sondage basé sur l’inférence statistique pour les totaux des échantillons, car les résultats totaux observés, tU, sont fixés à travers une randomisation. Nous pouvons utiliser des covariables pour augmenter la précision ici car l’estimateur de régression pour l’enquête nous permet d’estimer le total que nous aurions vu dans le groupe de contrôle : <span class="math inline">\(\hat{t}_c=\sum_{i∈U}\hat{Y}_i+ \sum_{i∈U}(Y_i-\hat{Y}_i)\)</span> avec <span class="math inline">\(\hat{Y}_i=f(X_i,\beta)\)</span> (Lohr 1999). La littérature sur l’échantillonnage pour les sondages montre que, comme <span class="math inline">\(N→∞\)</span>, <span class="math inline">\(CI(\hat{t}_c) \approx \hat{t}_c \pm z_{a/2}SE(\hat{t}_c)\)</span>. Ainsi, on peut calculer <span class="math inline">\(\widehat{SE}(\hat{t}_c)\)</span> à partir de la théorie de l’échantillonnage standard puis <span class="math inline">\(CI(\hat{A}) \approx t_U-\widehat{CI}(\hat{t }_c)\)</span>.</p>
<p>Dans le code ci-dessous, nous fournissons une illustration utilisant des données simulées pour une réponse binaire et un traitement. Pour 85 % du groupe de traitement, <span class="math inline">\(Y=1\)</span> comparativement à 52 % dans le groupe de contrôle. Une différence de cette taille est cohérente avec le fait que notre traitement a causé <span class="math inline">\(Y=1\)</span> pour 92 à 138 sujets, pour lesquels <span class="math inline">\(Y\)</span> aurait autrement été égal à 0 s’ils n’avaient pas reçu le traitement. L’estimateur de régression, qui tire parti de la précision obtenue en incluant des covariables, produit des intervalles de confiance plus serrés (de 98,8 à 135,1) pour les effets attribuables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># pour la reproductibilité</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># taille de la population</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Covariables</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># Probabilité inégale de traitement</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="fu">rnorm</span>(n)) <span class="co"># Résultats potentiels pour la réponse binaire</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">pnorm</span>(X1 <span class="sc">+</span> X2<span class="sc">+</span><span class="dv">1</span>) </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p0) </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p1) </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Résultat observé</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y,X1,X2)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>attribute<span class="ot">&lt;-</span><span class="cf">function</span>(treat,out,A,data){ </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Contingence de l'état du traitement et des résultats</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  attr.tab<span class="ot">&lt;-</span><span class="fu">with</span>(data,<span class="fu">table</span>(treat,out))</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Matrice des p-valeurs pour les effets attribuables, A</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  attr.ps<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="cn">NA</span>,<span class="at">nc=</span><span class="dv">2</span>,<span class="at">nr=</span>A,<span class="at">dimnames=</span><span class="fu">list</span>(<span class="cn">NULL</span>,<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"p"</span>)))</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>A){ </span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    attr.ps[i,]<span class="ot">&lt;-</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">c</span>(i,<span class="fu">fisher.test</span>(attr.tab<span class="sc">+</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,i,<span class="dv">0</span>,<span class="sc">-</span>i),<span class="dv">2</span>,<span class="dv">2</span>))<span class="sc">$</span>p) </span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Trouver la plage d'effets</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  get.bounds<span class="ot">&lt;-</span><span class="cf">function</span>(){ </span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    diffs<span class="ot">&lt;-</span><span class="fu">ifelse</span>(.<span class="dv">05</span><span class="sc">-</span>attr.ps[,<span class="st">"p"</span>]<span class="sc">&gt;</span><span class="dv">0</span>,.<span class="dv">05</span><span class="sc">-</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>                    attr.ps[,<span class="st">"p"</span>],<span class="dv">99</span>) </span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    index<span class="ot">&lt;-</span>(diffs <span class="sc">%in%</span> </span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(<span class="fu">min</span>(diffs),<span class="fu">min</span>(diffs[diffs<span class="sc">&gt;</span><span class="fu">min</span>(diffs)]))) </span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    index </span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Retourner la plage d'effets</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (attr.ps[<span class="fu">get.bounds</span>(),])</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(samp,<span class="fu">table</span>(D,Y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Y
D     0   1
  0 318 339
  1  51 292</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(samp,<span class="fu">apply</span>(<span class="fu">table</span>(D,Y),<span class="dv">1</span>,prop.table)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   D
Y           0        1
  0 0.4840183 0.148688
  1 0.5159817 0.851312</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attribute</span>(<span class="at">treat =</span> D, <span class="at">out=</span> Y, <span class="at">A=</span><span class="dv">200</span>,<span class="at">data=</span>samp) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       A          p
[1,]  92 0.04519869
[2,] 138 0.04587804</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimateur de régression</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>fit1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>samp,<span class="at">subset=</span>D<span class="sc">==</span><span class="dv">0</span>) </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>hatYcU<span class="ot">&lt;-</span><span class="fu">predict</span>(fit1,<span class="at">newdata=</span>samp) </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>ec<span class="ot">&lt;-</span>Y[D<span class="sc">==</span><span class="dv">0</span>]<span class="sc">-</span>hatYcU[D<span class="sc">==</span><span class="dv">0</span>] <span class="co"># idem aux residuals(fit1)</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>hatTotYc<span class="ot">&lt;-</span><span class="fu">sum</span>(hatYcU)<span class="sc">+</span><span class="fu">sum</span>(ec) </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>N<span class="ot">&lt;-</span><span class="fu">length</span>(Y) </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>nctrls<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="dv">1</span><span class="sc">-</span>D) </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>thefpc<span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> (nctrls<span class="sc">/</span>N)) </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>varhattC<span class="ot">&lt;-</span>N<span class="sc">*</span>thefpc<span class="sc">*</span><span class="fu">var</span>(Y[D<span class="sc">==</span><span class="dv">0</span>]) </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>alpha<span class="ot">&lt;-</span><span class="fu">c</span>(.<span class="dv">05</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>) </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>alpha<span class="ot">&lt;-</span><span class="fu">sort</span>(<span class="fu">c</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)) </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>ciTotYc<span class="ot">&lt;-</span>hatTotYc<span class="sc">+</span><span class="fu">sqrt</span>(varhattC)<span class="sc">*</span><span class="fu">qnorm</span>(alpha) </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>ciAE<span class="ot">&lt;-</span><span class="fu">sort</span>(<span class="fu">sum</span>(Y) <span class="sc">-</span> ciTotYc ) </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ciAE)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"&lt; 95%"</span>,<span class="st">"&lt; 66%"</span>,<span class="st">"&gt; 66%"</span>,<span class="st">"&gt; 95%"</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ciAE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    &lt; 95%     &lt; 66%     &gt; 66%     &gt; 95% 
 98.78637 107.97975 125.90114 135.09451 </code></pre>
</div>
</div>
</section>
<section id="références" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Références</h1>
<p>Aronow, Peter M et Joel A Middleton. 2013. “A Class of Unbiased Estimators of the Average Treatment Effect in Randomized Experiments.” Journal of Causal Inference 1 (1): 135–54.</p>
<p>Aronow, Peter M et Cyrus Samii. 2014. “Does Regression Produce Representative Estimates of Causal Effects?” In EPSA 2013 Annual General Conference Paper. Vol. 585.</p>
<p>Baron, Reuben M et David A Kenny. 1986. “The Moderator–Mediator Variable Distinction in Social Psychological Research: Conceptual, Strategic, and Statistical Considerations.” Journal of Personality and Social Psychology 51 (6). American Psychological Association: 1173.</p>
<p>Bound, John, David A Jaeger et Regina M Baker. 1995. “Problems with Instrumental Variables Estimation When the Correlation Between the Instruments and the Endogenous Explanatory Variable Is Weak.” Journal of the American Statistical Association 90 (430). Taylor &amp; Francis: 443–50.</p>
<p>Brambor, Thomas, William R. Clark et Matt Golder. 2006. “Understanding Interaction Models: Improving Empirical Analyses.” Political Analysis 14 (1): 63–82.</p>
<p>Bullock, John G, Donald P Green et Shang E Ha. 2010. “Yes, but What’s the Mechanism?(don’t Expect an Easy Answer).” Journal of Personality and Social Psychology 98 (4). American Psychological Association: 550.</p>
<p>Chernozhukov, Victor et Christian Hansen. 2005. “An IV Model of Quantile Treatment Effects.” Econometrica 73 (1). Wiley Online Library: 245–61.</p>
<p>Dunning, Thad. 2010. “Design-Based Inference: Beyond the Pitfalls of Regression Analysis?” Rethinking Social Inquiry: Diverse Tools, Shared Standards. 2nd Ed. Lanham, Md.: Rowman and Littlefield.</p>
<p>Freedman, David A. 2008a. “On Regression Adjustments to Experimental Data.” Advances in Applied Mathematics 40 (2). Elsevier: 180–93. ———. 2008b. “Randomization Does Not Justify Logistic Regression.” Statistical Science 23 (2). Institute of Mathematical Statistics: 237–49.</p>
<p>Frölich, Markus et Blaise Melly. 2010. “Estimation of Quantile Treatment Effects with Stata.” Stata Journal 10 (3): 423.</p>
<p>Gerber, Alan S et Donald P Green. 2012. Field Experiments: Design, Analysis, and Interpretation. WW Norton.</p>
<p>Green, Donald P. 2009. “Regression Adjustments to Experimental Data: Do David Freedman’s Concerns Apply to Political Science?” In 26th Annual Meeting of the Society for Political Methodology, Yale University, July, 23–25.</p>
<p>Hansen, Ben et Jake Bowers. 2009. “Attributing Effects to a Cluster-Randomized Get-Out-the-Vote Campaign.” Journal of the American Statistical Association 104 (487). Taylor &amp; Francis: 873–85.</p>
<p>Hartman, Erin, RD Grieve, R Ramsahai et Jasjeet S Sekhon. forthcoming. “From SATE to PATT: Combining Experimental with Observational Studies.” Journal of the Royal Statistical Society.</p>
<p>Hirano, Keisuke, Guido W Imbens et Geert Ridder. 2003. “Efficient Estimation of Average Treatment Effects Using the Estimated Propensity Score.” Econometrica 71 (4). Wiley Online Library: 1161–89.</p>
<p>Holland, Paul W. 1986. “Statistics and Causal Inference.” Journal of the American Statistical Association 81 (396). Taylor &amp; Francis: 945–60.</p>
<p>Imai, K., L. Keele, D. Tingley et T. Yamamoto. 2011. “Unpacking the Black Box of Causality: Learning About Causal Mechanisms from Experimental and Observational Studies.” American Political Science Review 105 (4). Cambridge Univ Press: 765–89.</p>
<p>Imai, Kosuke et Teppei Yamamoto. 2013. “Identification and Sensitivity Analysis for Multiple Causal Mechanisms: Revisiting Evidence from Framing Experiments.” Political Analysis 21 (2). SPM-PMSAPSA: 141–71.</p>
<p>Imai, Kosuke, Luke Keele et Teppei Yamamoto. 2010. “Identification, Inference and Sensitivity Analysis for Causal Mediation Effects.” Statistical Science. JSTOR, 51–71.</p>
<p>Imai, Kosuke, Gary King et Elizabeth A Stuart. 2008. “Misunderstandings Between Experimentalists and Observationalists About Causal Inference.” Journal of the Royal Statistical Society: series A (Statistics in Society) 171 (2). Wiley Online Library: 481–502.</p>
<p>Imai, Kosuke, Dustin Tingley et Teppei Yamamoto. 2013. “Experimental Designs for Identifying Causal Mechanisms.” Journal of the Royal Statistical Society: Series A (Statistics in Society) 176 (1). Wiley Online Library: 5–51.</p>
<p>Lin, Winston. 2013. “Agnostic Notes on Regression Adjustments to Experimental Data: Reexamining Freedman’s Critique.” The Annals of Applied Statistics 7 (1). Institute of Mathematical Statistics: 295–318.</p>
<p>Lohr, Sharon L. 1999. “Sampling: DesignandAnalysis.” Pacific Grove, CA: Brooks/Cole.</p>
<p>Neyman, Jerzy. 1990 [1923]. “On the Application of Probability Theory to Agricultural Experiments. Essay on Principles. Section 9.” Statistical Science 5 (4). Institute of Mathematical Statistics: 465–72 (Translated by D.M. Dabrowska and T.P. Speed from the original Polish).</p>
<p>Nickerson, D.W. 2008. “Is Voting Contagious? Evidence from Two Field Experiments.” American Political Science Review 102 (1). Cambridge Univ Press: 49.</p>
<p>Rosenbaum, Paul. 2002. “Attributing Effects to Treatment in Matched Observational Studies.” Journal of the American Statistical Association 97 (457). Taylor &amp; Francis: 183–92.</p>
<p>Rosenbaum, Paul R. 2002. Observational Studies. Springer.</p>
<p>Rosenbaum, Paul et Donald B. Rubin. 1983. “The Central Role of the Propensity Score in Observational Studies for Causal Effects.” Biometrika 70 (1). Biometrika Trust: 41–55.</p>
<p>Rosenbaum, Paul et Jeffrey H Silber. 2008. “Aberrant Effects of Treatment.” Journal of the American Statistical Association 103 (481). Taylor &amp; Francis: 240–47.</p>
<p>Rosenbaum, PR. 2010. “Design of Observational Studies.” Springer Series in Statistics. New York [etc.]: Springer. Tingley, Dustin, Teppei Yamamoto, Kentaro Hirose, Luke Keele et Kosuke Imai. 2014. “mediation: R Package for Causal Mediation Analysis.” Journal of Statistical Software 59 (5): 1–38. http://www.jstatsoft.org/v59/i05/.</p>


</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Voir Holland (1986), Angrist et Pischke, Angrist, Joshua et Jörn-Steffen Pischke (2008). Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton University Press.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Voir Holland et Angrist &amp; Pischke encore une fois pour une discussion plus formelle de l’indépendance et des hypothèses nécessaires pour estimer les effets causaux.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>i.e <span class="math inline">\((E(Y_i(1)|D=1)=E(Y_i(1)|D=0)=E(Y_i(1)))\)</span> et <span class="math inline">\((E(Y_i(0)|D=1)=E(Y_i(0)|D=0)=E(Y_i(0)))\)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Les estimations sont souvent écrites avec un chapeau (<span class="math inline">\(\widehat{ATE}\)</span>) pour refléter la différence entre l’estimation de notre échantillon particulier et le paramètre, cible de notre estimation qui n’est pas observée. Sauf indication contraire, dans ce guide, nous nous concentrons sur la génération d’estimations d’échantillons et omettons par la suite cette notation explicite par souci de concision. Voir Gerber et Green (2012) pour une introduction concise à cette distinction et Imbens et Wooldridge (2007) pour un traitement approfondi de ces concepts.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>La covariance de <span class="math inline">\(Y_{i}(1),Y_{i}(0)\)</span> est impossible à observer mais l’estimateur “Neyman” de la variance en omettant le terme de covariance fournit une estimation conservatrice (trop grande) de la vraie variance de l’échantillon parce que nous avons tendance à supposer que la covariance est positive. Étant donné que nous sommes généralement soucieux de minimiser le taux d’erreur de type I (rejetant à tort l’hypothèse nulle vraie), nous préférons utiliser des estimations conservatrices de la variance. Voir aussi Dunning (2010) et Gerber &amp; Green (2012) pour la justification de l’estimateur de variance conservateur.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Lin (2013)<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Brambor, Clark et Golder (2006)<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Angrist, Joshua et Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Nous supposons généralement la monotonie, ce qui signifie qu’il n’y a pas de non-conformistes, c’est à dire de personnes qui ne prennent le traitement que lorsqu’elles sont assignées au contrôle (<span class="math inline">\(D_{i}=1\)</span> quand <span class="math inline">\(Z_i=0\)</span>) et refusent le traitement lorsqu’elles sont assignées au traitement (<span class="math inline">\(D_{i}=0\)</span> quand <span class="math inline">\(Z_{i}=1\)</span>).<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Angrist, Joshua et Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.; Bound, Jaeger, and Baker (1995)<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Imai, King et Stuart (2008) pour un examen plus détaillé des questions abordées dans cette section.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Imbens, Guido et Jeffrey M Wooldridge. 2007. What’s New in Econometrics? NBER.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Angrist et Pischke (2008) fournissent une brève introduction des sujets traités plus en détail par Hirano, Imbens et Ridder (2003), Aronow et Middleton (2013), Glynn et Quinn (2010), et Hartman et al.&nbsp;(à paraître)<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Glynn, Adam N et Kevin M Quinn. 2010. “An Introduction to the Augmented Inverse Propensity Weighted Estimator.” Political Analysis 18 (1):36–56.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Hartman et al.&nbsp;(à paraître) pour voir les efforts visant à combiner des données expérimentales et observationnelles pour passer d’un ATE pour un échantillon à un ATT pour une population.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Rosenbaum et Rubin (1983)<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Abadie, Angrist et Imbens (2002)<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Chernozhukov et Hansen (2005). C’est-à-dire que le traitement peut avoir des effets hétérogènes, mais l’ordre des résultats potentiels est préservé. Voir Angrist, Joshua et Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Voir Koenker, Roger et Kevin Hallock. 2001. “Quantile Regression: An Introduction.” Journal of Economic Perspectives 15 (4): 43–56. pour un aperçu concis de la régression par quantile<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Formellement, Imai, Keele et Yamamoto (2010) définissent les conditions nécessaires d’ignorabilité séquentielle comme : <span class="math inline">\({Y_i(d',m),M_i(d)}⊥D_i|X_i=x, Y_i(d',m)⊥M_i(d)|D_i=d,X_i=x\)</span>. C’est-à-dire que, premièrement, étant donné les covariables de pré-traitement, les résultats potentiels de Y et M sont indépendants du traitement D et, deuxièmement, conditionnés aux covariables de pré-traitement et au statut du traitement, les résultats potentiels sont également indépendants du médiateur.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>Voir par exemple Imai, Keele et Yamamoto (2010), Imai et al.&nbsp;(2011), Imai, Tingley et Yamamoto (2013), ou Imai et Yamamoto (2013). Aussi voir la discussion de Imai, Tingley et Yamamoto (2013) pour différentes perspectives quand aborder une affirmation sur la médiation avec une analyse de sensibilité ou une analyse des bornes de sensibilité.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/methods\.egap\.org");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>