<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paul Testa">

<title>10 tipos de los efectos causales que debe conocer – Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../img/egap-logo.svg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../guides.html"> 
<span class="menu-text">Methods guides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../software.html"> 
<span class="menu-text">Software</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.en.html">Language</a></li><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.es.html"><img src="https://flagcdn.com/w20/es.png" width="20px">&nbsp;&nbsp;Spanish</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/how-to-read.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to read this guide</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true">
 <span class="menu-text">Language</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.en.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><img src="https://flagcdn.com/w20/gb.png" width="20px">&nbsp;&nbsp;English</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.fr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><img src="https://flagcdn.com/w20/fr.png" width="20px">&nbsp;&nbsp;French</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guides/research-questions/effect-types.es.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><img src="https://flagcdn.com/w20/es.png" width="20px">&nbsp;&nbsp;Spanish</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.en.html">Language</a></li><li class="breadcrumb-item"><a href="../../guides/research-questions/effect-types.es.html"><img src="https://flagcdn.com/w20/es.png" width="20px">&nbsp;&nbsp;Spanish</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">10 tipos de los efectos causales que debe conocer</h1>
</div>

<div class="quarto-title-meta">
    
    
    
    
</div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Summary</div>
    <p>Esta guía<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> presenta una discusión más formal de la independencia y de los supuestos necesarios para estimar los efectos causales. Además, describe diez tipos distintos de efectos causales en los que podríamos estar interesados. Como demostramos en nuestra guía de inferencia causal, la aleatorización simple permite producir estimaciones del promedio de los efectos causales al nivel de la unidad en una muestra. Este efecto causal promedio o efecto promedio del tratamiento (Average Treatment Effect, ATE) es un concepto poderoso porque provee una solución al problema de no poder observar todos los contrafactuales relevantes para la estimación. Sin embargo, no es la unica forma de abordar este problema. De hecho, hay muchas cantidades de interés causal diferentes. El objetivo de esta guía es ayudarlo a elegir estimandos (un parámetro de interés) y estimadores (procedimientos para calcular estimaciones de esos parámetros) que sean apropiados y significativos para sus datos.</p>
  </div>
</div>
</header>

<nav id="TOC" role="doc-toc">
    <h4 id="toc-title">Contents</h4>
   
  <ul>
  <li><a href="#efecto-promedio-del-tratamiento" id="toc-efecto-promedio-del-tratamiento"><span class="header-section-number">1</span> Efecto promedio del tratamiento</a></li>
  <li><a href="#efecto-condicional-promedio-del-tratamiento" id="toc-efecto-condicional-promedio-del-tratamiento"><span class="header-section-number">2</span> Efecto condicional promedio del tratamiento</a></li>
  <li><a href="#efectos-de-la-intención-de-tratar" id="toc-efectos-de-la-intención-de-tratar"><span class="header-section-number">3</span> Efectos de la intención de tratar</a></li>
  <li><a href="#efectos-de-tratamiento-promedio-para-los-que-cumplen" id="toc-efectos-de-tratamiento-promedio-para-los-que-cumplen"><span class="header-section-number">4</span> Efectos de tratamiento promedio para los que cumplen</a></li>
  <li><a href="#efectos-promedio-del-tratamiento-en-la-población-y-la-muestra" id="toc-efectos-promedio-del-tratamiento-en-la-población-y-la-muestra"><span class="header-section-number">5</span> Efectos promedio del tratamiento en la población y la muestra</a></li>
  <li><a href="#efecto-promedio-del-tratamiento-en-el-grupo-de-tratamiento-y-el-control" id="toc-efecto-promedio-del-tratamiento-en-el-grupo-de-tratamiento-y-el-control"><span class="header-section-number">6</span> Efecto promedio del tratamiento en el grupo de tratamiento y el control</a></li>
  <li><a href="#efecto-promedio-cuantil-del-tratamiento" id="toc-efecto-promedio-cuantil-del-tratamiento"><span class="header-section-number">7</span> Efecto promedio cuantil del tratamiento</a></li>
  <li><a href="#efectos-de-mediación" id="toc-efectos-de-mediación"><span class="header-section-number">8</span> Efectos de mediación</a></li>
  <li><a href="#efectos-del-tratamiento-con-probabilidades-logarítmicas" id="toc-efectos-del-tratamiento-con-probabilidades-logarítmicas"><span class="header-section-number">9</span> Efectos del tratamiento con probabilidades logarítmicas</a></li>
  <li><a href="#efectos-atribuibles" id="toc-efectos-atribuibles"><span class="header-section-number">10</span> Efectos atribuibles</a></li>
  <li><a href="#referencias" id="toc-referencias"><span class="header-section-number">11</span> Referencias</a></li>
  </ul>
</nav>
<section id="efecto-promedio-del-tratamiento" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Efecto promedio del tratamiento</h1>
<p>Comenzamos revisando cómo, con la aleatorización, una simple diferencia de medias proporciona una estimación no sesgada del ATE. A continuación, presentamos algunos conceptos estadísticos comunes y la notación que utilizamos a lo largo de esta guía.</p>
<p>Primero definimos el efecto del tratamiento para una observación individual (una persona, hogar, ciudad, etc.) como la diferencia entre el comportamiento de esa unidad bajo tratamiento <span class="math inline">\((Y_ {i} (1))\)</span> y su control <span class="math display">\[\tau_{i}=Y_{i}(1)-Y_{i}(0).\]</span> Dado que solo podemos observar $Y_{i}(1) $ o <span class="math inline">\(Y_ {i} (0)\)</span>, no tenemos forma de saber cuál es el efecto del tratamiento individual. Ahora sea <span class="math inline">\(D_{i}\)</span> un indicador de si una observación está en el grupo de tratamiento o control. Si el tratamiento se asigna al azar, <span class="math inline">\(D_ {i}\)</span> es independiente, no solo de los resultados potenciales sino también de cualquier covariable (observada y no observada) que pueda predecir también esos resultados <span class="math inline">\(((Y_ {i} (1), Y_ {i } (0),X_ {i} \perp \perp D_ {i}))\)</span> <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Suponga que nuestro diseño tiene <span class="math inline">\(m\)</span> unidades en el grupo de tratamiento y <span class="math inline">\(N - m\)</span> en el de control. Supongamos que reasignamos repetidamente el tratamiento al azar muchas veces y cada vez calculamos la diferencia de medias entre los grupos de tratamiento y de control y luego registramos este valor en una lista. El promedio de los valores en esa lista será el mismo que la diferencia de los promedios de los resultados potenciales reales si hubiéramos observado todos los resultados potenciales posibles para todas las observaciones <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Otra forma de expresar esta característica del efecto promedio del tratamiento y el estimador del mismo es decir que la diferencia de medias observadas es un estimador insesgado del efecto del tratamiento causal promedio.</p>
<p><span class="math display">\[ATE\equiv\frac{1}{N}\sum^{N}_{i=1}\tau_{i}=\frac{\sum^{N}_{1}Y_{i}(1)}{N}-\frac{\sum^{N}_{1}Y_{i}(0)}{N}\]</span></p>
<p>A menudo estimamos el ATE utilizando la diferencia de medias observada: <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p><span class="math display">\[\widehat{ATE} =\frac{\sum^m_1Z_{i}Y_{i}}{m}-\frac{\sum^{N}_{m+1}(1-Z_{i})Y_{i}}{N-m}\]</span></p>
<p>La inferencia estadística sobre el ATE estimado requiere que sepamos cómo este variaría entre cada aleatorización. Para eso podemos escribir la varianza entre aleatorizaciones de la siguiente manera:</p>
<p><span class="math display">\[V(ATE) = \frac{N}{N-1} [\frac{V(Y_{i}(1))}{m}+\frac{V(Y_{i}(0))}{N-m}]-\frac{1}{N-1}[V(Y_{i}(1))+V(Y_{i}(0))-2Cov(Y_{i}(1),Y_{i}(0))]\]</span></p>
<p>y estimar esta cantidad a partir de las estimaciones muestrales de la varianza en cada grupo. <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Un modelo lineal que regresa el resultado observado <span class="math inline">\(Y_ {i}\)</span> en un indicador de la asignación del tratamiento <span class="math inline">\(D_{i}\)</span> nos sirve como estimador del ATE (y con algunos ajustes adicionales de la varianza del ATE):</p>
<p><span class="math display">\[Y_{i}=Y_{i}(0)(1-D_{i})+Y_{i}(1)D_{i}=\beta_{0}+\beta_{1}D_{i}+u\]</span> ya que podemos reorganizar los términos de modo que <span class="math inline">\(\beta_{0}\)</span> estime el promedio entre las observaciones de control <span class="math inline">\((Y_ {i} (0) ∣D_ {i} = 0)\)</span> y <span class="math inline">\(\beta_{1}\)</span> estime las diferencias de las medias <span class="math inline">\((Y_ {i} (1) ∣D_ {i} = 1) - (Y_ {i} (1) ∣D_ {i} = 0)\)</span>. En el siguiente código, creamos una muestra de 1000 observaciones y asignamos aleatoriamente un tratamiento <span class="math inline">\(D_i\)</span> con un efecto constante para la mitad de las unidades. Estimamos el ATE utilizando la regresión de mínimos cuadrados ordinarios (MCO) para calcular la diferencia de medias observada. El cálculo de las medias en cada grupo y su diferencia también produciría una estimación no sesgada del ATE. Tenga en cuenta que el ATE estimado del estimador de MCO es insesgado porque suponemos que los errores en este modelo lineal son independientes y están distribuidos de manera idéntica. Cuando nuestro tratamiento afecta tanto al valor promedio del resultado como a la distribución de las respuestas, esta supuesto ya no se cumple y necesitamos ajustar los errores estándar de MCO utilizando un estimador sándwich de Huber-White para obtener las estimaciones correctas (basadas en la varianza del ATE) para hacer inferencia estadística. <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Finalmente, a través de la simulación demostramos que estos estimadores son insesgados.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Por replicabilidad </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la población</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(N) <span class="co"># Resultado potencial bajo la condición de control</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="co"># Resultado potencial bajo la condición de tratamiento</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>N)<span class="sc">%%</span><span class="dv">2</span>) <span class="co">#igual a 1 si la unidad es tratada, 0 de lo contrario</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Variable de resultado de la población</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y) </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ATE <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp))[<span class="dv">2</span>] <span class="co">#lo mismo que with(samp,mean(Y[Z==1])-mean(Y[Z==0])) </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ATE de la muestra (SATE) con error estándar Neyman </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># o justificados en la aleatorización</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># que son iguales al error estándar del MCO cuando no hay covariables o bloques</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest) </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich) </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp) </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(fit))[<span class="st">"D"</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Estimate Std. Error 
1.01820525 0.01841784 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ATE.se<span class="ot">&lt;-</span><span class="fu">coeftest</span>(fit,<span class="fu">vcovHC</span>(fit,<span class="at">type=</span><span class="st">"HC2"</span>))[<span class="st">"D"</span>,<span class="dv">2</span>] </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a> <span class="co">#lo mismo que with(samp,sqrt(var(Y[D==1])/sum(D)+var(Y[D==0])/(n-sum(D))) </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar si no hay sesgo y simular el error estándar</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>getATE<span class="ot">&lt;-</span><span class="cf">function</span>() {</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>N)<span class="sc">%%</span><span class="dv">2</span>) <span class="co">#  igual a 1 si la unidad es tratada, 0 de lo contrario</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D))[[<span class="st">"D"</span>]] </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>manyATEs<span class="ot">&lt;-</span><span class="fu">replicate</span>(<span class="dv">10000</span>,<span class="fu">getATE</span>()) </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Sesgo</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">ATE=</span><span class="fu">mean</span>(Y1)<span class="sc">-</span><span class="fu">mean</span>(Y0), <span class="at">ExpEstATE=</span><span class="fu">mean</span>(manyATEs)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      ATE ExpEstATE 
1.0000000 0.9999077 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Error estándar</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Fórmula del error estándar real</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>V<span class="ot">&lt;-</span><span class="fu">var</span>(<span class="fu">cbind</span>(Y0,Y1)) </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>varc<span class="ot">&lt;-</span>V[<span class="dv">1</span>,<span class="dv">1</span>] </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>vart<span class="ot">&lt;-</span>V[<span class="dv">2</span>,<span class="dv">2</span>] </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>covtc<span class="ot">&lt;-</span>V[<span class="dv">1</span>,<span class="dv">2</span>] </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="fu">sum</span>(D) </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span>N<span class="sc">-</span>n </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>varestATE<span class="ot">&lt;-</span>((N<span class="sc">-</span>n)<span class="sc">/</span>(N<span class="dv">-1</span>))<span class="sc">*</span>(vart<span class="sc">/</span>n) <span class="sc">+</span> ((N<span class="sc">-</span>m)<span class="sc">/</span>(N<span class="dv">-1</span>))<span class="sc">*</span> (varc<span class="sc">/</span>m) <span class="sc">+</span> (<span class="dv">2</span><span class="sc">/</span>(N<span class="dv">-1</span>)) <span class="sc">*</span> covtc </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="do">### Compararar errores estándar </span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SimulatedSE=</span> <span class="fu">sd</span>(manyATEs), <span class="at">TrueSE=</span><span class="fu">sqrt</span>(varestATE), <span class="at">ConservativeSE=</span>ATE.se) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   SimulatedSE         TrueSE ConservativeSE 
    0.01835497     0.01842684     0.01841784 </code></pre>
</div>
</div>
</section>
<section id="efecto-condicional-promedio-del-tratamiento" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Efecto condicional promedio del tratamiento</h1>
<p>El problema de enfocarse únicamente el efecto promedio del tratamiento es que desvía la atención del hecho de que los efectos del tratamiento pueden ser muy diferentes para diferentes tipos de personas. Si bien el “problema fundamental de la inferencia causal” sugiere que medir los efectos causales para unidades individuales es imposible, hacer inferencias sobre grupos de unidades no lo es.</p>
<p>La asignación aleatoria asegura que el tratamiento sea independiente de las variables de resultado y de cualquier covariable (observada y no observada). Sin embargo, a veces tenemos información adicional sobre las unidades experimentales tal como eran antes de que se realizara el experimento. Denotaremos esta información como <span class="math inline">\(X_{i}\)</span>. <span class="math inline">\(X_{i}\)</span> puede ayudarnos a comprender cómo los efectos del tratamiento varían entre los subgrupos. Por ejemplo, podemos sospechar que los hombres y las mujeres responden de manera diferente al tratamiento, y podemos probar esta hetorogeneidad estimando el ATE condicional para cada subgrupo por separado <span class="math inline">\((CATE = E (Y_{i} (1) -Y_{i} (0)∣D_ {i}, X_{i}))\)</span>. Si nuestra covariable es continua podemos probar sus efectos moderadores interactuando la variable continua con el tratamiento. Sin embargo, tenga en cuenta que el efecto del tratamiento ahora está condicionado tanto al estado del tratamiento como al valor de la variable condicionante en la que se evalúa el efecto, por lo que debemos ajustar nuestra interpretación y los errores estándar en consecuencia.[^7]</p>
<p>Una advertencia: enfocarse en los efectos del tratamiento en las dimensiones que se ven afectadas por el tratamiento es peligroso y puede conducir a inferencias incorrectas. Por ejemplo, si quisiera ver cómo la administración de un medicamento produce mejoras en la salud, podría buscar por separado a hombres y mujeres, pero no podría buscar por separado a los que tomaron el medicamento y a los que no (este es un ejemplo de inferencia para que los que cumplen con la asignación al tramiento y este tipo de inferencia requiere otras técnicas descritas en el punto 4).</p>
</section>
<section id="efectos-de-la-intención-de-tratar" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Efectos de la intención de tratar</h1>
<p>Fuera de un entorno de laboratorio controlado, los sujetos que asignamos al tratamiento a menudo no son los mismos que los sujetos que realmente reciben el tratamiento. Cuando algunos sujetos asignados al tratamiento no lo reciben, lo llamamos un experimento con incumplimiento unilateral. Cuando además, algunos sujetos asignados al control también reciben el tratamiento, decimos que hay un incumplimiento bilateral. Por ejemplo, en un experimento para promover la votación electoral, es posible que algunas sujetos asignados para recibir una carta no lo reciban. Quizás hayan cambiado de dirección o nunca hayan revisado su correo. De manera similar, algunas observaciones asignadas al control pueden recibir el tratamiento. Quizás se acaban de mudar y el correo del inquilino anterior todavía llega a ese domicilio.</p>
<p>Cuando hay incumplimiento, la recepción del tratamiento ya no es independiente de las variable resultados y posibles factores que puedan generar distorsión. Las personas que realmente leen su correo probablemente difieran en varias formas de las personas que tiran su correo (o leen el correo ajeno) y estas diferencias probablemente también afecten su probabilidad de votar. La diferencia de medias entre los sujetos asignados al tratamiento y al control ya no estima el ATE, sino que estima lo que se llama un efecto por intención de tratar (Intention to treat, ITT). A menudo interpretamos el ITT como el efecto de darle a alguien la oportunidad de recibir el tratamiento. El ITT es particularmente relevante para evaluar programas e intervenciones con participación voluntaria.</p>
<p>En el siguiente código, generamos datos con incumplimiento unilateral. Aunque el verdadero efecto del tratamiento para las personas que realmente recibieron el tratamiento es 2, nuestro ITT estimado es menor (aproximadamente 1) porque solo algunas de las personas asignadas al tratamiento realmente lo reciben.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Por replicabilidad</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la población</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Resultado potencial bajo el control</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>C <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Si el sujeto cumple con la asignación</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span>C <span class="co"># Resultado potencial bajo el tratamiento </span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Asignación al tratamiento</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> Z<span class="sc">*</span>C <span class="co"># Indicador de si recibe el tratamiento</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Variable de resultado</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(Z,Y)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>ITT<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>Z,<span class="at">data=</span>samp))[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="efectos-de-tratamiento-promedio-para-los-que-cumplen" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Efectos de tratamiento promedio para los que cumplen</h1>
<p>¿Qué pasa si estamos interesado en averiguar los efectos de un tratamiento en aquellas personas que realmente recibieron el tratamiento y no solo en aquellas personas a las que se les asignó el tratamiento? Por ejemplo, ¿cuál es el efecto de los anuncios de radio en el comportamiento de voto de las personas que realmente escuchan los anuncios?</p>
<p>Esto resulta ser un problema difícil de abordar (en esta guía puede encontrar más información al respecto). Las razones del incumplimiento del tratamiento pueden ser una variable omitida. Si bien la recepción del tratamiento ya no es independiente de los posibles resultados, la asignación del estado del tratamiento sí lo es. Siempre que la asignación aleatoria tenga algún efecto positivo sobre la probabilidad de recibir tratamiento, podemos usarlo como un instrumento para identificar los efectos del tratamiento en la subpoblación de sujetos que cumplen con la asignación al tratamiento.</p>
<p>Siguiendo la notación de Angrist y Pischke <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>, sea <span class="math inline">\(Z\)</span> un indicador de si se asignó una observación al tratamiento y <span class="math inline">\(D_{i}\)</span> indica si ese sujeto realmente recibió el tratamiento. Los experimentos con incumplimiento están compuestos por personas que siempre toman el tratamiento (<span class="math inline">\(D_{i} = 1\)</span>, independientemente de $ Z_{i}<span class="math inline">\(), personas que nunca lo toman (\)</span>D_ {i} = 0$ independientemente de <span class="math inline">\(Z_ {i}\)</span>) y los que cumplen con la asignación (<span class="math inline">\(D_ {i} = 1\)</span> cuando $Z_{i} = 1 $ y <span class="math inline">\(0\)</span> cuando <span class="math inline">\(Z_ {i} = 0\)</span>).<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> Podemos estimar un efecto causal promedio del cumplidor (Complier Average Causal Effect, CACE), a veces también llamado efecto de tratamiento promedio local (LATE, Local Average Treatment Effect), al ponderar el ITT (el efecto de <span class="math inline">\(Z\)</span> en <span class="math inline">\(Y\)</span>) por la efectividad de la asignación aleatoria en la aceptación del tratamiento (el efecto de <span class="math inline">\(Z\)</span> en $ D$)</p>
<p><span class="math display">\[CACE= \frac{Effect of Z on Y}{Effect of Z on D}=\frac{E(Y_i∣Z_i=1)-E(Y_i|Z_i=0)}{E(D_i|Z_i=1)-E(D_i|Z_i=0)}\]</span></p>
<p>El estimador anterior destaca el hecho de que el ITT y el CACE convergen a medida que nos acercamos a un cumplimiento total. Construir errores estándar para fracciones es algo engorroso, por lo que generalmente estimamos un CACE usando regresión de mínimos cuadrados de dos etapas con asignación aleatoria, <span class="math inline">\(Z_i\)</span>, que sirve como instrumento para la recepción del tratamiento <span class="math inline">\(D_i\)</span> en la primera etapa del modelo. Este enfoque simplifica la estimación de errores estándar y permite la inclusión de covariables como instrumentos adicionales. Presentamos ambas estrategias en el siguiente código utilizando datos con incumplimiento bilateral. Sin embargo, tenga en cuenta que cuando los instrumentos son débiles (por ejemplo, la asignación aleatoria tuvo solo un efecto pequeño en la recepción del tratamiento), los estimadores de variables instrumentales y sus errores estándar pueden ser sesgados e inconsistentes <a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Por replicabilidad</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la población</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Resultado potencial bajo el control</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="co"># Resultado potencial bajo el tratamiento </span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Asignación al tratamiento</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pD<span class="ot">&lt;-</span><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">+</span><span class="fu">rnorm</span>(n,<span class="at">mean=</span><span class="dv">2</span><span class="sc">*</span>Z)) <span class="co"># Incumplimiento</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>D<span class="ot">&lt;-</span><span class="fu">rbinom</span>(n,<span class="dv">1</span>,pD) <span class="co"># Recepción del tratamiento sin incumplimiento</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Variable de resultado</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(Z,D,Y) </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># IV estimate library(AER) CACE = coef(ivreg(Y ~ D | Z, data = samp))[2] </span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Wald Estimator ITT&lt;-coef(lm(Y~Z,data=samp))[2] ITT.D&lt;-coef(lm(D~Z,data=samp))[2] CACE.wald&lt;-ITT/ITT.D</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="efectos-promedio-del-tratamiento-en-la-población-y-la-muestra" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Efectos promedio del tratamiento en la población y la muestra</h1>
<p>A menudo queremos hacer generalizaciones a partir de nuestra muestra para poder hacer afirmaciones sobre una población de interés más amplia <a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. Sea <span class="math inline">\(S_i\)</span> un indicador de si un sujeto está en nuestra muestra. El efecto de tratamiento promedio de la muestra (Sample Average Treatment Effect, SATE) se define simplemente como <span class="math inline">\(E(Y_i (1) -Y_i(0) | S_i = 1)\)</span> y la población <span class="math inline">\(E(Y_i (1) -Y_i (0))\)</span>. Con una muestra aleatoria grande de una población bien definida y con cumplimiento total de la asignación al tratamiento, el SATE y el PATE (ATE de la población) son iguales en expectativa y, por lo tanto, una buena estimación para uno (como una diferencia de medias muestrales) será una buena estimación para el otro. <a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>En la práctica, el grupo experimental puede consistir de un grupo de unidades seleccionadas de una manera desconocida de una población vagamente definida de tales unidades y el cumplimiento de la asignación de tratamiento puede ser menos que completo. En tales casos, nuestro SATE puede diferir del PATE y utilizar uno para estimar el otro se vuelve más complicado. Imai, King y Stuart (2008) descomponen la diferencia entre estas estimaciones en un error que surge de la selección de la muestra y el imbalance del tratamiento. El error de la selección de la muestra surge de diferentes distribuciones de covariables (observadas y no observadas) en nuestra muestra y población. Por ejemplo, las personas en un ensayo médico a menudo difieren de la población para la que estaría disponible el medicamento. El error de imbalance del tratamiento refleja las diferencias en las covariables entre los grupos de tratamiento y de control en nuestra muestra, quizás debido a una asignación no aleatoria y /o al incumplimiento.</p>
<p>Si bien no existen soluciones simples para los problemas creados por este tipo de error, existen pasos que puede seguir tanto en el diseño de su estudio como en el análisis de sus datos para abordar los retos que implican estimar el PATE o CACE/ LATE. Por ejemplo, la inclusión de una intervención con placebo proporciona información adicional sobre la probabilidad de recibir el tratamiento, que puede usarse para volver a ponderar el efecto de recibirlo realmente (vea, por ejemplo, Nickerson (2008)) cuando hay incumplimiento. También se podría utilizar un modelo para volver a ponderar las observaciones para ajustar el imbalance de covariables y la probabilidad desigual de recibir el tratamiento, tanto dentro de la muestra como entre una muestra y la población de interés. [^13]</p>
<p>[^ 13]: Angrist y Pischke (2008) proporcionan una breve introducción de los temas tratados con más detalle por Hirano, Imbens y Ridder (2003), Aronow y Middleton (2013), Glynn y Quinn (2010) y Hartman et al.(Próximo a publicación)</p>
<p>En el código presentado a continuación mostramos varios enfoques para estimar estos efectos implementados en el paquete CausalGAM de R <a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>. Específicamente, el paquete para hacer regresiones, ponderación de propensión inversa ( Inverse Propensity Weighting, IPW) y estimaciones de ponderación de propensión inversa aumentada del ATE. Combinando el ajuste de regresión con IPW, el AIPW tiene la característica de ser “doblemente robusto” en el sentido de que la estimación sigue siendo consistente incluso si hemos especificado incorrectamente el modelo de regresión o el puntaje de propensión para la ponderación de probabilidad. .</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejemplo adapdato de ?estimate.ATE </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CausalGAM) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Por replicabilidad</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la muestra</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Covariables de pre-tratamiento</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># Probabilidad desigual del tratamiento</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) <span class="co"># Tratamiento</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Resultados potenciales </span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span> X1 <span class="sc">+</span> X2 </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Variable de resultado observada</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X1,X2,D,Y) </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimar el ATE con AIPW, IPW, pesos de la regresión</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>ATE.out <span class="ot">&lt;-</span> <span class="fu">estimate.ATE</span>(<span class="at">pscore.formula =</span> D <span class="sc">~</span> X1 <span class="sc">+</span>X2, </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                        <span class="at">pscore.family =</span> binomial, </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.formula.t =</span> Y <span class="sc">~</span> X1 </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span>X2, </span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.formula.c =</span> Y <span class="sc">~</span> X1 </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span>X2, </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                        <span class="at">outcome.family =</span> gaussian, </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                        <span class="at">treatment.var =</span> <span class="st">"D"</span>, </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data=</span>samp, </span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>                        <span class="at">divby0.action=</span><span class="st">"t"</span>, </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>                        <span class="at">divby0.tol=</span><span class="fl">0.001</span>, </span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>                        <span class="at">var.gam.plot=</span><span class="cn">FALSE</span>, <span class="at">nboot=</span><span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="efecto-promedio-del-tratamiento-en-el-grupo-de-tratamiento-y-el-control" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Efecto promedio del tratamiento en el grupo de tratamiento y el control</h1>
<p>Para evaluar las implicaciones en políticas públicas de una intervención en particular, a menudo necesitamos conocer los efectos del tratamiento no solo para toda la población, sino específicamente para aquellos a quienes se administra el tratamiento. Definimos los efectos promedio del tratamiento entre los tratados (Average Treatment effect on the Treated. ATT) y el grupo de control (Average Treatment effect on the Control, ATC) como simples comparaciones contrafactuales:</p>
<p><span class="math display">\[ATT=E(Y_i(1)-Y_i(0)|D_i=1)=E(Y_i(1)|D_i=1)-E(Y_i(0)|D_i=1)\]</span> <span class="math display">\[ATC=E(Y_i(1)-Y_i(0)|D_i=0)=E(Y_i(1)|D_i=0)-E(Y_i(0)|D_i=0)\]</span> Informalmente, el ATT es el efecto para aquellos que tratamos. El ATC es cuál <em>sería</em> el efecto para aquellos que no tratamos.</p>
<p>Cuando el tratamiento se asigna al azar y hay cumplimiento total, el <span class="math inline">\(ATE= ATT =ATC\)</span>, ya que <span class="math inline">\(E(Y_i (0) ∣D_i = 1) = E (Y_i (0) ∣D_i = 0)\)</span> y <span class="math inline">\(E ( Y_i (1) ∣D_i = 0) = E (Y_i (1) ∣D_i = 1)\)</span>. A menudo, ya sea por la naturaleza de la intervención o por preocupaciones específicas sobre el costo y la etnia, el cumplimiento del tratamiento es incompleto y el ATE en general no será igual al ATT o ATC. En tales casos, como vimos en la sección anterior podemos volver a ponderar las observaciones por la probabilidad de que reciban el tratamiento para poder estimar el ATE. La misma lógica puede extenderse para producir estimaciones del ATT y ATC tanto en nuestra muestra como en la población <a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a>.</p>
<p>A continuación, creamos datos en los que la probabilidad de recibir el tratamiento varía, pero puede estimarse mediante un modelo de puntaje de propensión (propensity score model en inglés) <a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a>. Las probabilidades predecidas por este modelo se utilizan luego para ponderar y poder estimar el ATE, ATT y ATC. La ponderación inversa del puntaje de propensión intenta equilibrar la distribución de las covariables entre los grupos de tratamiento y control al estimar el ATE. Para el ATT, este enfoque de ponderación trata a los sujetos en el grupo de tratamiento como una muestra de la población objetivo (personas que recibieron el tratamiento) y hace una ponderación de los sujetos en el grupo de control según sus probabilidades de recibir el tratamiento. De manera similar, la estimación de los pesos del ATC trata las observaciones para que sirvan como unidades de control. La calidad (ausencia de sesgo) de estas estimaciones está intrínsecamente vinculada a la calidad de nuestros modelos para predecir la recepción del tratamiento. La ponderación inversa del puntaje de propensión y otros procedimientos producen balance en las covariables observadas entre los grupos de tratamiento y control, pero a menos que tengamos el “modelo verdadero” (y casi nunca conocemos el modelo verdadero), el potencial de sesgo de las covariables no observadas se mantiene y debería llevarnos a interpretar nuestro ATT o ATC estimado a la luz de la calidad del modelo que lo produjo.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Para la replicación</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la muestra</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Covariables de pre-tratamiento</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># Propabilidad desigual de asignación al tratamiento</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) <span class="co"># Tratamiento</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Resultados potencial</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span><span class="dv">1</span> <span class="sc">+</span>X1 <span class="sc">+</span>X2 </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Resultados observados</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X1,X2,D,Y) </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo de puntaje de propensión</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>p.score<span class="ot">&lt;-</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(<span class="fu">glm</span>(D<span class="sc">~</span>X1<span class="sc">+</span>X2,samp,<span class="at">family=</span>binomial),<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Pesos inversos de la probabilidad</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.ipw<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span><span class="sc">/</span>p.score,<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p.score))) </span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.att<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,<span class="dv">1</span>,p.score<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p.score))) </span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>samp<span class="sc">$</span>W.atc<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">ifelse</span>(D<span class="sc">==</span><span class="dv">1</span>,(<span class="dv">1</span><span class="sc">-</span>p.score)<span class="sc">/</span>p.score,<span class="dv">1</span>)) </span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># IPW: ATE, ATT, ATC </span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>ATE.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.ipw))[<span class="dv">2</span>]</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>ATT.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.att))[<span class="dv">2</span>] </span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>ATC.ipw<span class="ot">&lt;-</span><span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp,<span class="at">weights=</span>W.atc))[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="efecto-promedio-cuantil-del-tratamiento" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Efecto promedio cuantil del tratamiento</h1>
<p>El ATE se enfoca en en el punto medio que es de alguna manera el efecto para una observación típica, pero a menudo también nos preocupan las consecuencias distributivas de nuestro tratamiento. Queremos saber no solo si nuestro tratamiento aumentó el ingreso promedio, sino también si hizo que la distribución del ingreso en el estudio fuera más o menos igual.</p>
<p>Hacer afirmaciones sobre distribuciones es difícil. Aunque podemos estimar el ATE a partir de una diferencia de medias muestrales, en general, no podemos hacer afirmaciones sobre la distribución conjunta de los resultados potenciales <span class="math inline">\((F(Y_i (1), Y_i(0)))\)</span> sin suposiciones adicionales. Por lo general, estos supuestos limitan nuestro análisis a una subpoblación específica <a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> o nos obligan a asumir alguna forma de invariancia de rango en la distribución de las respuestas a los efectos del tratamiento <a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a>. Puede ver <a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> y Frölich y Melly (2010) para una discusión concisa sobre estos temas y Abbring and Heckman (Abbring, Jaap H, y James J Heckman. 2007. “Econometric Evaluation of Social Programs, Part III: Distributional Treatment Effects, Dynamic Treatment Effects, Dynamic Discrete Choice, and General Equilibrium Policy Evaluation.” Handbook of Econometrics 6. Elsevier: 5145–5303.) (2007) para una revisión general de estos temas.</p>
<p>Si estos supuestos están justificados para nuestros datos, podemos obtener estimaciones consistentes del efecto promedio cuantil del tratamiento (Quantile Treatment Effect, QTE) utilizando la regresión por cuantiles <a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a>. Así como la regresión lineal estima el ATE como una diferencia en las medias (o, cuando se utilizan covariables en el modelo, a partir de una media condicional), la regresión por cuantiles ajusta un modelo lineal a un cuantil condicional y este modelo se puede utilizar para estimar los efectos del tratamiento para ese cuantil particular del resultado. El enfoque se puede ampliar para incluir covariables e instrumentos para considerar casos en los que hay incumplimiento. Tenga en cuenta que la interpretación del QTE es para un cuantil dado, no para un individuo en ese cuantil.</p>
<p>A continuación mostramos un caso en el que el ATE es 0, pero el efecto del tratamiento es negativo para respuestas en cuantiles bajos y positivo para cuantiles altos. La estimación del efecto cuantil del tratamiento sirve como herramienta para detectar efectos heterogéneos y nos permite describir las consecuencias distributivas de nuestra intervención. Estos conocimientos adicionales tienen el costo de requerir supuestos estadísticos más estrictos de nuestros datos e interpretaciones más matizadas de nuestros resultados.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Por replicabilidad</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la población</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Resultados potencial bajo la condición de control</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>Y1<span class="ot">=</span> Y0 </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>Y1[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>] <span class="ot">=</span> Y0[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>]<span class="sc">-</span><span class="fu">rnorm</span>(<span class="fu">length</span>(Y0[Y0 <span class="sc">&lt;</span>.<span class="dv">5</span>])) </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>Y1[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>] <span class="ot">=</span> Y0[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>]<span class="sc">+</span><span class="fu">rnorm</span>(<span class="fu">length</span>(Y0[Y0 <span class="sc">&gt;</span>.<span class="dv">5</span>])) </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Tratamiento: 1 si tratado 0 de lo contrario </span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co"># Variable de resultado de la población </span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y) </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantreg) </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ATE <span class="ot">=</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Y<span class="sc">~</span>D,<span class="at">data=</span>samp))[<span class="dv">2</span>] </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>QTE <span class="ot">=</span> <span class="fu">rq</span>(Y<span class="sc">~</span>D,<span class="at">tau =</span> </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(.<span class="dv">05</span>,.<span class="dv">95</span>,<span class="at">length.out=</span><span class="dv">10</span>),<span class="at">data=</span>samp,<span class="at">method =</span> <span class="st">"fn"</span>) </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">summary</span>(QTE),<span class="at">parm=</span><span class="dv">2</span>,<span class="at">main=</span><span class="st">""</span>,<span class="at">ylab=</span><span class="st">"QTE"</span>,<span class="at">xlab=</span><span class="st">"Quantile"</span>,<span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">2.1</span>, <span class="fl">2.1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="effect-types.es_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="efectos-de-mediación" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Efectos de mediación</h1>
<p>A veces queremos describir no solo la magnitud y el significado de un efecto causal observado, sino también el mecanismo (o mecanismos) que lo produjeron. ¿Nuestra intervención aumentó la participación en el grupo de tratamiento, en parte, porque aumentó el sentido de eficacia política de estos sujetos? Si es así, ¿cuánto de ese efecto total puede atribuirse a los efectos mediados por nuestro tratamiento en la eficacia y de la eficacia en la participación?</p>
<p>Baron y Kenny (1986) ofrecen un marco general para pensar en la mediación al descomponer el efecto total del tratamiento en su efecto indirecto sobre un mediador que luego afecta el resultado, llamado efecto de mediación causal promedio (Average Causal Mediation Effect, ACME), y el efecto directo promedio restante (emaining Average Direct Effect, ADE) del tratamiento. Sin embargo, la estimación insesgada de estos efectos requiere un conjunto de supuestos sólidos sobre la relación entre el tratamiento, los mediadores, los resultados y los posibles factores que pueden generar distorsión, denominados colectivamente ignorabilidad secuencial (Imai, Keele y Yamamoto (2010), Bullock, Green y Ha (2010). )). <a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
<p>La mayoría de los efectos causales probablemente operan a través de múltiples canales, por lo que una suposición de ignorabilidad secuencial para un experimento puede ser difícil de justificar. Por ejemplo, la fila superior en la figura siguiente ilustra situaciones en las que se mantiene la ignorabilidad secuencial, mientras que la fila inferior muestra dos (de muchos posibles) casos en los que se viola la ignorabilidad secuencial y el análisis de mediación está sesgado. En esencia, especificar los efectos de un mediador en particular requiere suposiciones sólidas sobre el papel de todos los demás mediadores en la cadena causal. Si bien algunos diseños experimentales pueden, en teoría, proporcionar un apalancamiento adicional (como ejecutar un segundo experimento paralelo en el que también se manipula al mediador), en la práctica estos diseños son difíciles de implementar y sensibles a sesgos no observados. En algunos casos, los conocimientos que esperamos obtener del análisis de mediación pueden adquirirse más fácilmente a partir de análisis de subgrupos y experimentos diseñados para probar la moderación.</p>
<p>Imai y colegas proponen un enfoque para el análisis de mediación que permite a los investigadores probar la sensibilidad de sus estimaciones a violaciones de ignorabilidad secuencial<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a>. En el código presentado a continuación mostramos algunas de las características de este enfoque, implementadas en el paquete <code>mediation</code> en R (Tingley et al.2014). Modelamos las relaciones utilizando MCO, pero el paquete es capaz de manejar otros modelos, como modelos lineales generalizados o modelos aditivos generales, que pueden ser más apropiados para sus datos. Más importante aún, el paquete nos permite producir límites que reflejan la sensibilidad de nuestras estimaciones puntuales a algunas violaciones de ignorabilidad secuencial. En nuestros datos simulados, poco más del 20 por ciento del efecto total está mediado por nuestro mediador propuesto, M, y el sesgo de un factor de distorsión previo al tratamiento no observado tendría que ser bastante grande (<span class="math inline">\(\rho\)</span> = .7) antes de que rechacemos el hallazgo de un ACME positivo. Sin embargo, estos límites solo son válidos si creemos que no hay factores no observados postratamiento que causen distorsión (como en el panel 4). El análisis de sensibilidad es posible, pero más complicado en tales entornos (Imai y Yamamoto 2013).</p>
<p><img src="https://raw.githubusercontent.com/egap/methods-guides/master/effect-types/effect-types_fig2_esp.png" class="img-fluid"></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Para replicar</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la muestra</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Resultado potencial bajo el control</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">sample</span>((<span class="dv">1</span><span class="sc">:</span>n)<span class="sc">%%</span><span class="dv">2</span>) <span class="co"># Tratamiento: 1 si tratado, 0 de lo contrario</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">rnorm</span>(n) <span class="co"># Covariables</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>M<span class="ot">&lt;-</span><span class="fu">rnorm</span>(<span class="at">n=</span>n,<span class="at">mean=</span>D<span class="sc">+</span><span class="fu">rnorm</span>(n)) <span class="co"># Mediador influenciado por el tratamiento</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> Y0 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">+</span> M <span class="co">#  Resultado potencial bajo el tratamiento</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co">#  Variable de resultado de la población </span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>samp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(D,M,Y) </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation) </span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>med.f<span class="ot">&lt;-</span><span class="fu">lm</span>(M<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp) <span class="co"># Modelo para el mediador</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>out.f<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>M<span class="sc">+</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp) <span class="co"># Modelo para la variable de resultado</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Estimado del ACME y el  ADE </span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation) </span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>med.out<span class="ot">&lt;-</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mediate</span>(med.f,out.f,<span class="at">treat=</span><span class="st">"D"</span>,<span class="at">mediator=</span><span class="st">"M"</span>,<span class="at">robustSE=</span>T,<span class="at">sims=</span><span class="dv">1000</span>) </span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Sensibilidad del ACME a variables que no observadas que </span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co"># pueden generar distorsión</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>s.out<span class="ot">&lt;-</span><span class="fu">medsens</span>(med.out) </span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(s.out) <span class="co"># Grafica limites de sensibilidad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="effect-types.es_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="efectos-del-tratamiento-con-probabilidades-logarítmicas" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Efectos del tratamiento con probabilidades logarítmicas</h1>
<p>Los efectos promedio del tratamiento parecen un poco difíciles de interpretar cuando los resultados no son continuos. Por ejemplo, un resultado binario muy común en el estudio de las elecciones se codifica como 1 cuando los sujetos votaron y 0 cuando no lo hicieron. El efecto promedio podría ser 0.2, pero ¿qué significa realmente decir que un tratamiento aumentó mi voto en 0.2? La estimación de los efectos causales de los resultados dicotómicos requiere un cuidado adicional, en particular cuando se incluyen covariables. Una cantidad común de interés causal para los resultados dicotómicos es el efecto de nuestro tratamiento sobre las probabilidades de éxito logarítmicas, definidas para el grupo experimental como:</p>
<p><span class="math display">\[\Delta = log\frac{E(Y_i(1))}{1-E(Y_i(1))} - log\frac{E(Y_i(0))}{1-E(Y_i(0))}\]</span> Freedman (2008b) muestra que la regresión logística ajustada por covariables en experimentos aleatorios produce estimaciones sesgadas de este efecto causal. La intuición básica del argumento de Freedman proviene del hecho de que tomar el logaritmo de promedios no es lo mismo que tomar el promedio de logaritmos y, por lo tanto, el coeficiente de tratamiento estimado a partir de un condicionamiento de regresión logística sobre covariables no proporcionará un estimador consistente de probabilidades logarítmicas de éxito. Freedman recomienda en cambio tomar las probabilidades pronosticadas que varían el estado de tratamiento de los sujetos, pero manteniendo sus perfiles de covariables observados para producir un estimador consistente de las probabilidades logarítmicas.</p>
<p>El procedimiento básico se describe en el código presentado a continuación. Los coeficientes de la regresión logística que controlan la covariable X tienden a sobrestimar el efecto del tratamiento en las probabilidades logarítmicas, mientras que las estimaciones ajustadas de las probabilidades predecidas producen resultados consistentes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Para replicar </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de muestra</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>U <span class="ot">=</span> <span class="fu">runif</span>(n) </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">runif</span>(n) <span class="co"># Covariables obsersvadas</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">ifelse</span>(U<span class="sc">&gt;</span>.<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">0</span>) <span class="co"># Resultados potenciales</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> <span class="fu">ifelse</span>(U<span class="sc">+</span>X<span class="sc">&gt;</span>.<span class="dv">75</span>,<span class="dv">1</span>,<span class="dv">0</span>) </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n,<span class="dv">1</span>,.<span class="dv">75</span>) <span class="co"># Asignar aleatoriamente 3/4 al tratamiento </span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1<span class="sc">+</span>Y0<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>D) </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(X,D,Y) </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>aT<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">mean</span>(Y[D<span class="sc">==</span><span class="dv">1</span>])) </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>aC<span class="ot">&lt;-</span><span class="fu">with</span>(samp, <span class="fu">mean</span>(Y[D<span class="sc">==</span><span class="dv">0</span>])) </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># log odds incondicional</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>log.odds<span class="ot">&lt;-</span><span class="fu">log</span>(aT<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>aT))<span class="sc">-</span><span class="fu">log</span>(aC<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>aC)) </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión logística condicionando en X estima el log odds por encima</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">glm</span>(Y<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp,<span class="fu">binomial</span>(<span class="st">"logit"</span>)) </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>log.odds.logit<span class="ot">&lt;-</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="fu">glm</span>(Y<span class="sc">~</span>D<span class="sc">+</span>X,<span class="at">data=</span>samp,<span class="fu">binomial</span>(<span class="st">"logit"</span>)))[<span class="dv">2</span>] </span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframes tilizando covariables originales para las probabilidades de predicción</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>D1<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">D=</span><span class="dv">1</span>,samp[,<span class="fu">c</span>(<span class="st">"X"</span>)]) </span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>D0<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">D=</span><span class="dv">0</span>,samp[,<span class="fu">c</span>(<span class="st">"X"</span>)]) </span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="co"># log-odds ajustado produce un estimador consistente del log-odds </span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>aT.adj<span class="ot">&lt;-</span><span class="fu">predict</span>(fit,<span class="at">newdata=</span>D1,<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>aC.adj<span class="ot">&lt;-</span><span class="fu">predict</span>(fit,<span class="at">newdata=</span>D0,<span class="at">type=</span><span class="st">"response"</span>) </span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>log.odds.adj<span class="ot">&lt;-</span><span class="fu">log</span>(<span class="fu">mean</span>(aT.adj)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(aT.adj)))<span class="sc">-</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(<span class="fu">mean</span>(aC.adj)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(aC.adj)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="efectos-atribuibles" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Efectos atribuibles</h1>
<p>Concluimos con una breve discusión de un caso alternativo de interés causal que puede ser particularmente útil con resultados binarios: el efecto atribuible (Rosenbaum 2010). Considere un caso simple con un resultado y un tratamiento dicotómicos. Sea <span class="math inline">\(A\)</span> el número de resultados atribuibles al tratamiento, es decir, el número de casos en los que <span class="math inline">\(Y_i\)</span> es igual a 1 entre los sujetos tratados y que de haber sido asginados al control no habrían producido el mismo resultado. Para un rango de <span class="math inline">\(A\)</span>, ajustamos la tabla de contingencia observada de resultados entre las unidades tratadas y comparamos esta distribución resultante con una distribución nula conocida (la distribución de resultados que hubiéramos observado si el tratamiento no hubiera tenido efecto). El rango resultante de <span class="math inline">\(A\)</span> para el cual nuestra prueba continúa rechazando la hipótesis nula de ningún efecto proporciona un rango de efectos que son atribuibles a nuestro tratamiento.</p>
<p>Tabla 1|<span class="math inline">\(D=1\)</span> |<span class="math inline">\(D=0\)</span> ——-|——————-|————– <span class="math inline">\(Y=1\)</span> |<span class="math inline">\(\sum Y_iD_i-A\)</span> |<span class="math inline">\((1-Y_i)(D_i)\)</span> <span class="math inline">\(Y=0\)</span> |<span class="math inline">\(\sum Y_i(1-D_i)+A\)</span>|<span class="math inline">\(\sum (1-Y_i)(1-D_i)\)</span></p>
<p>Rosenbaum (2002) presenta extensiones de este concepto para diferentes tipos de resultados (como las variables continuas). Se puede aplicar una lógica similar para detectar respuestas poco comunes, pero extremas al tratamiento (Rosenbaum y Silber 2008).</p>
<p>Hansen y Bowers (2009) utilizan este enfoque para identificar el número de votos adicionales atribuibles a diferentes intervenciones en un experimento para incentivar el voto con asignación al tratamiento por conglomerados e incumplimiento unilateral. Ellos muestran que en muestras grandes se puede aproximar el intervalo de confianza para los efectos atribuibles sin evaluar cada atribución. A continuación presentamos un ejemplo de ese enfoque en el que se utilizan covariables para aumentar la precisión.</p>
<p>En primer lugar, definimos un efecto atribuible como <span class="math inline">\(A=\sum_iZ_i\tau_i\)</span>, donde <span class="math inline">\(\tau_i=Y_i(1)-Y_i(0)\)</span> y <span class="math inline">\(y\in0,1\)</span> como se muestra en Rosenbaum (2002). Es decir, el efecto atribuible es el número de “sis” o “exitos” o otras respuestas de “1” entre las unidades tratadas que no hubieramos obtenido si estas unidades hubieran sido asignadas al grupo de control.</p>
<p>En segundo lugar, como puede darse cuenta si escribimos el set <span class="math inline">\(U\)</span> como el universo experimental, y el set de unidades en el grupo de control es un subconjuto de este universo, <span class="math inline">\(C\subseteq U\)</span>, por lo tanto podemos decir que <span class="math inline">\(\sum_{i\in C}Y_i-Y_i(0)=0\)</span>. Esto quiere decir que podemos representar <span class="math inline">\(A\)</span> utulizando totales: <span class="math display">\[A = \sum_{i=1}^NZ_i\tau_i=\sum_{i=1}^NZ_i(Y_i(1)-Y_i(0))=\sum_{i\notin C}y_i(1)-sum_{i\notin C}y_i(0)\]</span></p>
<span class="math display">\[  = \sum_{i\notin C}Y_i-\sum_{i\notin C}Y_i(0)=\sum_{i=1}^NY_i-\sum_{i=1}^NY_i(0)=t_U-t_C\]</span>
<center>
= total observado general (fijo y observado) - total variable de resultado cuando es asignada al grupo de control (no observado, para estimar)
</center>
<p>En tercer lugar, esta representación nos permite producir un intervalo de confianza basado en el diseño para A^ basándonos en la literatura de muestreo de encuestas sobre inferencia estadística para totales de muestra porque los resultados totales observados, tU, se fijan en las aleatorizaciones. Podemos usar covariables para aumentar la precisión aquí porque el estimador de regresión de la encuesta nos permite estimar el total que habríamos visto en el grupo de control: <span class="math inline">\(\hat{t}_c=\sum_{i\in U}\hat{Y}_i+\sum_{i\in U}(Y_i-\hat{Y}_i)\)</span> with <span class="math inline">\(\hat{Y}_i=f(X_i,\beta)\)</span> (Lohr 1999). La literatura the muestreo de encuestas prueba que a medida que <span class="math inline">\(N\rightarrow \infty\)</span>, <span class="math inline">\(CI(\hat{t}_c) \approx \hat{t}_c \pm z_{a/2}SE(\hat{t}_c)\)</span>. Por lo que se puede calcular <span class="math inline">\(\widehat{SE}(\hat{t}_c)\)</span> de acuerdo a la teoría estándar de muestreo y luego el <span class="math inline">\(CI(\hat{A}) \approx t_U-\widehat{CI}(\hat{t}_c)\)</span>.</p>
<p>En el siguiente código, proporcionamos una ilustración que utiliza datos simulados para una respuesta y un tratamiento binarios. En el 85 por ciento del grupo de tratamiento, <span class="math inline">\(Y = 1\)</span> en comparación con el 52 por ciento en el grupo de control. Una diferencia de este tamaño es consistente con que nuestro tratamiento fue la causa de que <span class="math inline">\(Y = 1\)</span> para entre 92 y 138 sujetos, para quienes <span class="math inline">\(Y\)</span> habría sido igual a 0 si no hubieran recibido el tratamiento. El estimador de regresión, que aprovecha la precisión obtenida al incluir covariables, produce intervalos de confianza más estrictos (98,8 a 135,1) para los efectos atribuibles.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># Para replicar </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">1000</span> <span class="co"># Tamaño de la muestra</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">=</span> <span class="fu">rnorm</span>(n) <span class="co"># Covariables</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">=</span> <span class="fu">rnorm</span>(n) </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.75</span><span class="sc">*</span>X2) <span class="co"># Probabilidad desigual </span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                           <span class="co"># de asignación al tratamiento </span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>D <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p) </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="fu">rnorm</span>(n)) <span class="co"># Resultados potenciales para variable binaria</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">pnorm</span>(X1 <span class="sc">+</span> X2<span class="sc">+</span><span class="dv">1</span>) </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>Y0 <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p0) </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">=</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p1) </span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> D<span class="sc">*</span>Y1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>D)<span class="sc">*</span>Y0 <span class="co">#  Variable de resultado observada</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">=</span> <span class="fu">data.frame</span>(D,Y,X1,X2) <span class="co"># Base de datos</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>attribute<span class="ot">&lt;-</span><span class="cf">function</span>(treat,out,A,data){ </span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Tabla de contigencia del estado del tratamiento</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># y la variable de resultado </span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  attr.tab<span class="ot">&lt;-</span><span class="fu">with</span>(data,<span class="fu">table</span>(treat,out)) <span class="co"># </span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Matriz de valores p para efectos atribuibles A</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  attr.ps<span class="ot">&lt;-</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">matrix</span>(<span class="cn">NA</span>,<span class="at">nc=</span><span class="dv">2</span>,<span class="at">nr=</span>A,<span class="at">dimnames=</span><span class="fu">list</span>(<span class="cn">NULL</span>,<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"p"</span>))) </span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>A){ </span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    attr.ps[i,]<span class="ot">&lt;-</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">c</span>(i,<span class="fu">fisher.test</span>(attr.tab<span class="sc">+</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,i,<span class="dv">0</span>,<span class="sc">-</span>i),<span class="dv">2</span>,<span class="dv">2</span>))<span class="sc">$</span>p) </span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Determina el rango de los efectos</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  get.bounds<span class="ot">&lt;-</span><span class="cf">function</span>(){ </span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    diffs<span class="ot">&lt;-</span><span class="fu">ifelse</span>(.<span class="dv">05</span><span class="sc">-</span>attr.ps[,<span class="st">"p"</span>]<span class="sc">&gt;</span><span class="dv">0</span>,.<span class="dv">05</span><span class="sc">-</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>                    attr.ps[,<span class="st">"p"</span>],<span class="dv">99</span>) </span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    index<span class="ot">&lt;-</span>(diffs <span class="sc">%in%</span> </span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(<span class="fu">min</span>(diffs),<span class="fu">min</span>(diffs[diffs<span class="sc">&gt;</span><span class="fu">min</span>(diffs)]))) </span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    index </span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Devuelve el rango de los efectos</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (attr.ps[<span class="fu">get.bounds</span>(),])</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(samp,<span class="fu">table</span>(D,Y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Y
D     0   1
  0 318 339
  1  51 292</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(samp,<span class="fu">apply</span>(<span class="fu">table</span>(D,Y),<span class="dv">1</span>,prop.table)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   D
Y           0        1
  0 0.4840183 0.148688
  1 0.5159817 0.851312</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attribute</span>(<span class="at">treat =</span> D, <span class="at">out=</span> Y, <span class="at">A=</span><span class="dv">200</span>,<span class="at">data=</span>samp) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       A          p
[1,]  92 0.04519869
[2,] 138 0.04587804</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimador de la regresión</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fit1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>samp,<span class="at">subset=</span>D<span class="sc">==</span><span class="dv">0</span>) </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>hatYcU<span class="ot">&lt;-</span><span class="fu">predict</span>(fit1,<span class="at">newdata=</span>samp) </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>ec<span class="ot">&lt;-</span>Y[D<span class="sc">==</span><span class="dv">0</span>]<span class="sc">-</span>hatYcU[D<span class="sc">==</span><span class="dv">0</span>] <span class="do">## lo mismo que residuals(fit1) </span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>hatTotYc<span class="ot">&lt;-</span><span class="fu">sum</span>(hatYcU)<span class="sc">+</span><span class="fu">sum</span>(ec) </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>N<span class="ot">&lt;-</span><span class="fu">length</span>(Y) </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>nctrls<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="dv">1</span><span class="sc">-</span>D) </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>thefpc<span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> (nctrls<span class="sc">/</span>N)) </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>varhattC<span class="ot">&lt;-</span>N<span class="sc">*</span>thefpc<span class="sc">*</span><span class="fu">var</span>(Y[D<span class="sc">==</span><span class="dv">0</span>]) </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>alpha<span class="ot">&lt;-</span><span class="fu">c</span>(.<span class="dv">05</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>) </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>alpha<span class="ot">&lt;-</span><span class="fu">sort</span>(<span class="fu">c</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)) </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>ciTotYc<span class="ot">&lt;-</span>hatTotYc<span class="sc">+</span><span class="fu">sqrt</span>(varhattC)<span class="sc">*</span><span class="fu">qnorm</span>(alpha) </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>ciAE<span class="ot">&lt;-</span><span class="fu">sort</span>(<span class="fu">sum</span>(Y) <span class="sc">-</span> ciTotYc ) </span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ciAE)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"limite bajo 95%"</span>,<span class="st">"limite bajo </span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="st">66%"</span>,<span class="st">"limite alto 66%"</span>,<span class="st">"llimite alto 95%"</span>) </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ciAE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  limite bajo 95% limite bajo \n66%   limite alto 66%  llimite alto 95% 
         98.78637         107.97975         125.90114         135.09451 </code></pre>
</div>
</div>
</section>
<section id="referencias" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Referencias</h1>
<p>Aronow, Peter M, y Joel A Middleton. 2013. “A Class of Unbiased Estimators of the Average Treatment Effect in Randomized Experiments.” Journal of Causal Inference 1 (1): 135–54.</p>
<p>Aronow, Peter M, y Cyrus Samii. 2014. “Does Regression Produce Representative Estimates of Causal Effects?” In EPSA 2013 Annual General Conference Paper. Vol. 585.</p>
<p>Baron, Reuben M, y David A Kenny. 1986. “The Moderator–Mediator Variable Distinction in Social Psychological Research: Conceptual, Strategic, and Statistical Considerations.” Journal of Personality and Social Psychology 51 (6). American Psychological Association: 1173.</p>
<p>Bound, John, David A Jaeger, y Regina M Baker. 1995. “Problems with Instrumental Variables Estimation When the Correlation Between the Instruments and the Endogenous Explanatory Variable Is Weak.” Journal of the American Statistical Association 90 (430). Taylor &amp; Francis: 443–50.</p>
<p>Brambor, Thomas, William R. Clark, y Matt Golder. 2006. “Understanding Interaction Models: Improving Empirical Analyses.” Political Analysis 14 (1): 63–82.</p>
<p>Bullock, John G, Donald P Green, y Shang E Ha. 2010. “Yes, but What’s the Mechanism?(don’t Expect an Easy Answer).” Journal of Personality and Social Psychology 98 (4). American Psychological Association: 550.</p>
<p>Chernozhukov, Victor, y Christian Hansen. 2005. “An IV Model of Quantile Treatment Effects.” Econometrica 73 (1). Wiley Online Library: 245–61.</p>
<p>Dunning, Thad. 2010. “Design-Based Inference: Beyond the Pitfalls of Regression Analysis?” Rethinking Social Inquiry: Diverse Tools, Shared Standards. 2nd Ed. Lanham, Md.: Rowman and Littlefield.</p>
<p>Freedman, David A. 2008a. “On Regression Adjustments to Experimental Data.” Advances in Applied Mathematics 40 (2). Elsevier: 180–93. ———. 2008b. “Randomization Does Not Justify Logistic Regression.” Statistical Science 23 (2). Institute of Mathematical Statistics: 237–49.</p>
<p>Frölich, Markus, y Blaise Melly. 2010. “Estimation of Quantile Treatment Effects with Stata.” Stata Journal 10 (3): 423.</p>
<p>Gerber, Alan S, y Donald P Green. 2012. Field Experiments: Design, Analysis, and Interpretation. WW Norton.</p>
<p>Green, Donald P. 2009. “Regression Adjustments to Experimental Data: Do David Freedman’s Concerns Apply to Political Science?” In 26th Annual Meeting of the Society for Political Methodology, Yale University, July, 23–25.</p>
<p>Hansen, Ben, y Jake Bowers. 2009. “Attributing Effects to a Cluster-Randomized Get-Out-the-Vote Campaign.” Journal of the American Statistical Association 104 (487). Taylor &amp; Francis: 873–85.</p>
<p>Hartman, Erin, RD Grieve, R Ramsahai, and Jasjeet S Sekhon. forthcoming. “From SATE to PATT: Combining Experimental with Observational Studies.” Journal of the Royal Statistical Society.</p>
<p>Hirano, Keisuke, Guido W Imbens, y Geert Ridder. 2003. “Efficient Estimation of Average Treatment Effects Using the Estimated Propensity Score.” Econometrica 71 (4). Wiley Online Library: 1161–89.</p>
<p>Holland, Paul W. 1986. “Statistics and Causal Inference.” Journal of the American Statistical Association 81 (396). Taylor &amp; Francis: 945–60.</p>
<p>Imai, K., L. Keele, D. Tingley, y T. Yamamoto. 2011. “Unpacking the Black Box of Causality: Learning About Causal Mechanisms from Experimental and Observational Studies.” American Political Science Review 105 (4). Cambridge Univ Press: 765–89.</p>
<p>Imai, Kosuke, y Teppei Yamamoto. 2013. “Identification and Sensitivity Analysis for Multiple Causal Mechanisms: Revisiting Evidence from Framing Experiments.” Political Analysis 21 (2). SPM-PMSAPSA: 141–71.</p>
<p>Imai, Kosuke, Luke Keele, y Teppei Yamamoto. 2010. “Identification, Inference and Sensitivity Analysis for Causal Mediation Effects.” Statistical Science. JSTOR, 51–71.</p>
<p>Imai, Kosuke, Gary King, and Elizabeth A Stuart. 2008. “Misunderstandings Between Experimentalists and Observationalists About Causal Inference.” Journal of the Royal Statistical Society: series A (Statistics in Society) 171 (2). Wiley Online Library: 481–502.</p>
<p>Imai, Kosuke, Dustin Tingley, and Teppei Yamamoto. 2013. “Experimental Designs for Identifying Causal Mechanisms.” Journal of the Royal Statistical Society: Series A (Statistics in Society) 176 (1). Wiley Online Library: 5–51.</p>
<p>Lin, Winston. 2013. “Agnostic Notes on Regression Adjustments to Experimental Data: Reexamining Freedman’s Critique.” The Annals of Applied Statistics 7 (1). Institute of Mathematical Statistics: 295–318.</p>
<p>Lohr, Sharon L. 1999. “Sampling: DesignandAnalysis.” Pacific Grove, CA: Brooks/Cole.</p>
<p>Neyman, Jerzy. 1990 [1923]. “On the Application of Probability Theory to Agricultural Experiments. Essay on Principles. Section 9.” Statistical Science 5 (4). Institute of Mathematical Statistics: 465–72 (Translated by D.M. Dabrowska and T.P. Speed from the original Polish).</p>
<p>Nickerson, D.W. 2008. “Is Voting Contagious? Evidence from Two Field Experiments.” American Political Science Review 102 (1). Cambridge Univ Press: 49.</p>
<p>Rosenbaum, Paul. 2002. “Attributing Effects to Treatment in Matched Observational Studies.” Journal of the American Statistical Association 97 (457). Taylor &amp; Francis: 183–92.</p>
<p>Rosenbaum, Paul R. 2002. Observational Studies. Springer.</p>
<p>Rosenbaum, Paul, and Donald B. Rubin. 1983. “The Central Role of the Propensity Score in Observational Studies for Causal Effects.” Biometrika 70 (1). Biometrika Trust: 41–55.</p>
<p>Rosenbaum, Paul, and Jeffrey H Silber. 2008. “Aberrant Effects of Treatment.” Journal of the American Statistical Association 103 (481). Taylor &amp; Francis: 240–47.</p>
<p>Rosenbaum, PR. 2010. “Design of Observational Studies.” Springer Series in Statistics. New York [etc.]: Springer. Tingley, Dustin, Teppei Yamamoto, Kentaro Hirose, Luke Keele, and Kosuke Imai. 2014. “mediation: R Package for Causal Mediation Analysis.” Journal of Statistical Software 59 (5): 1–38. http://www.jstatsoft.org/v59/i05/.</p>


</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Puede consultar Holland (1986), Angrist y Pischke Angrist, Joshua y Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton University Press.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Ver Holland, Angrist y Pischke para una discusión más formal sobre la independencia y los supuestos necesarios para estimar los efectos causales.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Es decir, <span class="math inline">\((E(Y_i(1)|D=1)=E(Y_i(1)|D=0)=E(Y_i(1)))\)</span> and <span class="math inline">\((E(Y_i(0)|D=1)=E(Y_i(0)|D=0)=E(Y_i(0)))\)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Las estimaciones a menudo se escriben con un acento (<span class="math inline">\(\widehat {ATE}\)</span>) para reflejar la diferencia entre la estimación de nuestra muestra particular y el estimando, es decir la cantidad objetivo de nuestra estimación que no podemos observar. A menos que se indique lo contrario, en esta guía nos enfocamos en generar estimaciones a partir de la muestra y posteriormente omitimos esta notación explícita. Ver Gerber y Green (2012) para una introducción concisa a esta distinción e Imbens y Wooldridge (2007) para una revisión completa de estos conceptos.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>La covarianza de <span class="math inline">\(Y_{i} (1), Y_ {i} (0)\)</span> es imposible de observar, pero el estimador “Neyman” de la varianza que omite el término de covarianza proporciona una estimación conservadora (demasiado grande) de la varianza muestral verdadera porque tendemos a suponer que la covarianza es positiva. Dado que en general nos preocupa minimizar la tasa de error de tipo I (rechazando incorrectamente la hipótesis nula verdadera), preferimos utilizar estimaciones conservadoras de la varianza. Ver también Dunning (2010) y Gerber y Green (2012) para la justificación del estimador de varianza conservador.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Lin (2013)<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Angrist, Joshua y Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Por lo general, asumimos monotonicidad, lo que significa que no hay quienes desobedecen o desafían la asignación o personas que solo toman el tratamiento cuando se les asigna el control (<span class="math inline">\(D_{i} = 1\)</span> cuando <span class="math inline">\(Z_i = 0\)</span> ) y rechazan el tratamiento cuando se les asigna al tratamiento.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Angrist, Joshua, and Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.; Bound, Jaeger, and Baker (1995)<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Vea Imai, King y Stuart (2008) para una revisión más detallada de los temas discutidos en esta sección.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Imbens, Guido y Jeffrey M Wooldridge. 2007. What’s New in Econometrics? NBER.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Glynn, Adam N y Kevin M Quinn. 2010. “An Introduction to the Augmented Inverse Propensity Weighted Estimator.” Political Analysis 18 (1):36–56.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>En Hartman et al.&nbsp;(próximo a publicar) puede encontrar un ejemplo en el que se combinan datos experimentales and observacionales para pasar de un ATE de la muestra a una estimación del ATT de la población.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Rosenbaum y Rubin (1983)<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Abadie, Angrist y Imbens (2002)<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Chernozhukov y Hansen (2005). Es decir, el tratamiento puede tener efectos heterogéneos pero se conserva el orden de los resultados potenciales. Ver Joshua Angrist y Jörn-Steffen Pischke. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton university press.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Koenker, Roger Y Kevin Hallock. 2001. “Quantile Regression: An Introduction.” Journal of Economic Perspectives 15 (4): 43–56 para una revisión concisa de la regresión por cuantiles.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Koenker, Roger Y Kevin Hallock. 2001. “Quantile Regression: An Introduction.” Journal of Economic Perspectives 15 (4): 43–56 para una revisión concisa de la regresión por cuantiles.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Imai, Keele y Yamamoto (2010) definen formalmente las condiciones necesarias para la ignorabilidad secuencial como: <span class="math inline">\({Y_i(d',m),M_i(d)}\perp D_i|X_i=x, Y_i(d',m)\perp M_i(d)|D_i=d,X_i=x\)</span>. Esto quiere decir, primero, dado unas covariables de pretatamiento, los resultados potenciales de Y y M son independientes del tratamiento D y segundo que condicionado a las covariables previas al tratamiento y al estado del tratamiento, los resultados potenciales también son independientes del mediador.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Vea por ejemplo Imai, Keele, y Yamamoto (2010), Imai et al.&nbsp;(2011), Imai, Tingley y Yamamoto (2013), Imai y Yamamoto (2013). Así como también Imai, Tingley, y Yamamoto (2013) para perspectivas diferentes en la desabi for different perspectives sobre la conveniencia de abordar hacer aserciones sobre posible mediación con análisis de sensibilidad o de límites (bounds).<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/methods\.egap\.org");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>